import Foundation
import CryptoKit

/// Pure text generators for every file radiusd / slapd reads. No I/O here so it stays unit-testable.
nonisolated enum ConfigGenerator {

    // MARK: FreeRADIUS

    /// `libdir` is passed in rather than derived from `frPrefix`: in a bundled build the
    /// rlm_*.dylib modules live in `Contents/Frameworks`, which is not `<prefix>/lib`.
    static func radiusdConf(base: String, frPrefix: String, libdir: String, doc: LabDocument) -> String {
        let s = doc.settings
        let context = PolicyContext(doc)
        return """
        # Generated by SheepRadius — edits are overwritten on Apply.
        name = radiusd
        base = "\(base)"
        prefix = "\(frPrefix)"
        exec_prefix = "${prefix}"
        sysconfdir = "${base}"
        localstatedir = "${base}"
        sbindir = "${prefix}/bin"
        raddbdir = "${base}/raddb"
        confdir = "${raddbdir}"
        certdir = "${base}/certs"
        logdir = "${base}/log"
        radacctdir = "${logdir}/radacct"
        run_dir = "${base}/run"
        db_dir = "${base}/run"
        libdir = "\(libdir)"
        pidfile = "${run_dir}/radiusd.pid"

        max_request_time = 30
        cleanup_delay = 5
        max_requests = 1024
        hostname_lookups = no

        # Nothing here is ever proxied — there is no `realm` or `suffix` module in `authorize`
        # and no `proxy.conf` — but `proxy_requests` defaults to **yes** (confirmed by reading
        # it back out of `radiusd -CX` on 3.2.10), and with it on, `limit_proxy_state = auto`
        # stays in its permissive mode. Turning it off is what lets 3.2.10 enforce the
        # BlastRADIUS (CVE-2024-3596) Proxy-State rules, and it is the first thing a network
        # engineer looks for.
        proxy_requests = no

        log {
        	destination = files
        	file = "${logdir}/radius.log"
        	auth = yes
        	auth_badpass = no
        	auth_goodpass = no
        }

        security {
        	max_attributes = 200
        	reject_delay = 1
        	status_server = yes
        }

        thread pool {
        	start_servers = 2
        	max_servers = 8
        	min_spare_servers = 1
        	max_spare_servers = 4
        	max_requests_per_server = 0
        }

        $INCLUDE clients.conf

        modules {
        	pap {
        	}
        	chap {
        	}
        	mschap {
        		use_mppe = yes
        		require_encryption = yes
        		require_strong = yes
        	}
        	files {
        		filename = "${confdir}/authorize"
        	}
        	always ok {
        		rcode = ok
        	}
        	# A Reject action in a rule calls this. `reject` is NOT an unlang keyword in 3.2 —
        	# without the instance the section fails to compile with
        	# `Failed to find "reject" as a module or policy`.
        	always \(RuleUnlang.rejectModule) {
        		rcode = reject
        	}
        	# The local weekday, for a rule with a weekday window. Neither &Current-Time nor
        	# &Time-Of-Day is ever true in an unlang condition (they are paircompare virtuals,
        	# usable only in the users file) and no % expansion gives a weekday, so rlm_date is
        	# the way to get one. Its xlat reads an attribute rather than a literal, so the
        	# rules park the epoch in a temporary integer first.
        	date \(RuleUnlang.weekdayModule) {
        		format = "%a"
        	}
        	eap {
        		default_eap_type = \(s.defaultEAP.rawValue)
        		timer_expire = 60
        		ignore_unknown_eap_types = no
        		max_sessions = 1024

        		md5 {
        		}
        		gtc {
        			auth_type = PAP
        		}
        		mschapv2 {
        			send_error = no
        		}
        		tls-config tls-common {
        			private_key_file = "${certdir}/server.key"
        			certificate_file = "${certdir}/server.pem"
        			ca_file = "${certdir}/ca.pem"
        			# Build 20, audit N-8. Without it EAP-TLS accepts any certificate this
        			# lab's CA signed as ANY User-Name, so a certificate issued for a
        			# visitor logs in as an administrator. With it the CN has to be the
        			# name being claimed. PEAP and TTLS present no client certificate and
        			# are unaffected.
        			check_cert_cn = %{User-Name}
        			# The revocation list the Certificates pane maintains. `ca_path` is a
        			# directory of hash-named files, which is the only place OpenSSL will
        			# look for a CRL — and `check_crl` fails EVERY handshake when the CA has
        			# no CRL at all, so the app writes an empty one from the first start and
        			# rewrites it with 3650 days on every start. A CRL that ages out fails
        			# closed, and that is not a diagnosable fault.
        			ca_path = "${certdir}/ca_path"
        			check_crl = yes
        			cipher_list = "DEFAULT"
        			tls_min_version = "1.2"
        			tls_max_version = "\(s.tlsMaxVersion)"
        			ecdh_curve = ""
        			cache {
        				enable = no
        			}
        		}
        		tls {
        			tls = tls-common
        		}
        		# Copying the request into the tunnel is what lets a rule test NAS-IP-Address,
        		# NAS-Identifier, NAS-Port-Type, Called-Station-Id or Calling-Station-Id for a
        		# tunnelled session: those attributes exist only in the OUTER request, while the
        		# real identity exists only in here. The tunnelled reply is carried back out —
        		# and a reject decided in here rejects the outer session too.
        		ttls {
        			tls = tls-common
        			default_eap_type = md5
        			copy_request_to_tunnel = yes
        			use_tunneled_reply = yes
        			virtual_server = "inner-tunnel"
        		}
        		peap {
        			tls = tls-common
        			default_eap_type = mschapv2
        			copy_request_to_tunnel = yes
        			use_tunneled_reply = yes
        			virtual_server = "inner-tunnel"
        		}
        	}
        }

        server default {
        	listen {
        		type = auth
        		ipaddr = *
        		port = \(s.authPort)
        	}
        	listen {
        		type = acct
        		ipaddr = *
        		port = \(s.acctPort)
        	}
        \(pipeline(indent: "\t", doc: doc, context: context, inner: false))
        	accounting {
        		ok
        	}
        }

        server inner-tunnel {
        \(pipeline(indent: "\t", doc: doc, context: context, inner: true))
        }

        """
    }

    /// The generated `post-auth`, on its own, for the Policy pane's Advanced view. Exactly the
    /// text that goes into the file, so what the pane shows cannot be a paraphrase.
    static func rulesUnlang(_ doc: LabDocument) -> String {
        let context = PolicyContext(doc)
        var out = "server default {\n" + postAuth(indent: "\t", doc: doc, context: context, inner: false) + "}\n"
        out += "\nserver inner-tunnel {\n" + postAuth(indent: "\t", doc: doc, context: context, inner: true) + "}\n"
        return out
    }

    private static func postAuth(indent i: String, doc: LabDocument, context: PolicyContext,
                                 inner: Bool) -> String {
        let body = RuleUnlang.postAuth(rules: doc.rules, context: context, customUnlang: doc.customUnlang,
                                       indent: i, inner: inner)
        return "\(i)post-auth {\n\(body)\(i)}\n"
    }

    private static func pipeline(indent i: String, doc: LabDocument, context: PolicyContext,
                                 inner: Bool) -> String {
        let rules = RuleUnlang.postAuth(rules: doc.rules, context: context,
                                        customUnlang: doc.customUnlang, indent: i, inner: inner)
        return """
        \(i)authorize {
        \(i)	chap
        \(i)	mschap
        \(i)	eap {
        \(i)		ok = return
        \(i)	}
        \(i)	files
        \(i)	pap
        \(i)}
        \(i)authenticate {
        \(i)	Auth-Type PAP {
        \(i)		pap
        \(i)	}
        \(i)	Auth-Type CHAP {
        \(i)		chap
        \(i)	}
        \(i)	Auth-Type MS-CHAP {
        \(i)		mschap
        \(i)	}
        \(i)	eap
        \(i)}
        \(i)post-auth {
        \(rules)\(i)}
        """
    }

    static func clientsConf(_ clients: [NASClient]) -> String {
        var out = """
        client localhost {
        	ipaddr = 127.0.0.1
        	secret = "\(quoted(localTestSecret))"
        	shortname = "localhost"
        }

        """
        for (n, c) in clients.enumerated() {
            let short = c.name.isEmpty ? "nas\(n + 1)" : c.name
            out += """
            client nas_\(n + 1) {
            	ipaddr = \(c.address)
            	secret = "\(quoted(c.secret))"
            	shortname = "\(quoted(short))"
            """ + "\n"
            // Build 20, audit N-6. Written only when it is on, so the clients.conf of a
            // lab that never touched the switch is byte-for-byte the one build 19 wrote
            // and the global default stays at 3.2.10's `auto`.
            if c.requireMessageAuthenticator {
                out += "\trequire_message_authenticator = yes\n"
            }
            out += "}\n"
        }
        return out
    }

    /// The FreeRADIUS `users`-format file.
    ///
    /// Since build 13 it carries **no reply items at all**: every attribute a user gets back is
    /// decided by the Policy pane's rule list in post-auth. What is left is the password and
    /// the identity the rules read — `Sheep-OU` and `Sheep-Group` — all of them check items,
    /// which is why an entry is a single line with nothing indented under it.
    static func authorize(_ users: [LabUser], groups: [LabGroup]) -> String {
        let byID = Dictionary(groups.map { ($0.id, $0) }, uniquingKeysWith: { first, _ in first })
        var out = ""
        for u in users where u.enabled && !u.username.isEmpty {
            let mine = u.groups.compactMap { byID[$0] }
            out += "\"\(quoted(u.username))\"\tCleartext-Password := \"\(quoted(u.password))\""
            out += identityCheckItems(for: u, groups: mine)
            out += "\n\n"
        }
        return out
    }

    /// **Every cleartext password this app holds for a directory account**, keyed lower-case.
    ///
    /// Two sources, and both of them mean "the app set this password":
    ///
    /// * `directoryPasswords` — set through the Users pane since build 17.
    /// * the seed table in `lab.json` — which is what **filled** an OpenLDAP directory in the
    ///   first place (`seedLDIF` hashes exactly these) and what an upgraded lab still carries.
    ///
    /// Leaving the second out is what broke the live suite at `5df081f`: a fresh lab's
    /// alice/bob/guest are in slapd *because the app put them there*, their passwords were in
    /// `lab.json` all along, and writing them as `NT-Password` instead took CHAP and EAP-MD5
    /// away from a lab that had them a build earlier — and PAP with them, because `rlm_pap`
    /// cannot verify against an NT hash either.
    ///
    /// `directoryPasswords` wins a collision: it is the more recent of the two by
    /// construction, being written every time the app sets a password.
    static func knownPasswords(localUsers: [LabUser],
                               directoryPasswords: [String: String]) -> [String: String] {
        var out: [String: String] = [:]
        for user in localUsers where !user.username.isEmpty && !user.password.isEmpty {
            out[user.username.lowercased()] = user.password
        }
        for (name, password) in directoryPasswords where !password.isEmpty {
            out[name.lowercased()] = password
        }
        return out
    }

    /// The same file, written from a **directory snapshot** — which since build 21 is the
    /// only thing it is ever written from while a directory is running.
    ///
    /// The difference that matters is the password, and it is not a choice this code makes:
    /// a directory does not give passwords back. So an account whose password **this app**
    /// set gets `Cleartext-Password` (every method works, including CHAP), and every other
    /// account gets `NT-Password` from the hash pulled out of the backend — which covers PAP,
    /// MS-CHAP and PEAP and does not cover CHAP (`RadiusAuthorize.chapNeedsCleartext`).
    ///
    /// A user with neither is written as a comment rather than skipped silently: the file is
    /// the first thing anyone reads when a login is rejected, and "alice is not in here at
    /// all" and "alice is in here with no password" are different problems.
    ///
    /// Both dictionaries are keyed by **lower-cased** username, because `sAMAccountName` is
    /// case-insensitive and `uid` is matched case-insensitively by slapd.
    static func authorize(snapshot: DirectorySnapshot, passwords: [String: String],
                          hashes: [String: String]) -> String {
        var out = ""
        for user in snapshot.users where user.enabled && !user.username.isEmpty {
            let key = user.username.lowercased()
            // Nothing in this app can produce a `%{`; a directory the app did not create can.
            // Writing it would hand radiusd an expansion in place of the value.
            let unsafe = ([user.username, user.ou] + user.groups + [passwords[key] ?? ""])
                .first { !isSafeForAuthorize($0) }
            if unsafe != nil {
                out += "# \(quoted(user.username)): left out — a name, OU, group or password "
                out += "contains \"%{\", which FreeRADIUS expands and cannot escape.\n\n"
                continue
            }
            if let password = passwords[key] {
                out += RadiusAuthorize.cleartextLine(username: user.username, password: password)
            } else if let hash = hashes[key], !hash.isEmpty,
                      let line = RadiusAuthorize.ntPasswordLine(username: user.username, hashHex: hash) {
                out += line
            } else {
                out += "# \(user.username): no password and no NT hash — the directory has the "
                out += "account, this app has never set its password, and the backend would not "
                out += "give up its hash.\n\n"
                continue
            }
            out += identityCheckItems(ou: user.ou, groups: user.groups)
            out += "\n\n"
        }
        out += machineEntries(snapshot: snapshot, hashes: hashes)
        return out
    }

    /// **The machine accounts, one entry per identity form** (build 24).
    ///
    /// A domain-joined Windows PC doing 802.1X before anybody has logged in authenticates as
    /// the *computer*, with the machine account's password inside PEAP-MSCHAPv2. Until this
    /// build the snapshot had no computers in it at all, so the server rejected a supplicant
    /// whose account was sitting in the directory the whole time.
    ///
    /// Five entries rather than one because Windows sends one of five different strings
    /// depending on version and profile, and nothing in the generated configuration rewrites
    /// `User-Name` on the way in — see `MachineIdentity` for why that is, and for the list.
    /// They all carry the same `NT-Password` and the same tag, so which one arrives makes no
    /// difference to the verdict or to a rule.
    ///
    /// **A machine with no hash is written as a comment, not skipped.** The commonest reason
    /// is a backend that would not give the hash up, and "BEST$ is not in this file at all"
    /// and "BEST$ is here with no password" are different problems to be looking at.
    static func machineEntries(snapshot: DirectorySnapshot, hashes: [String: String]) -> String {
        var out = ""
        for computer in snapshot.computers where computer.enabled {
            let forms = MachineIdentity.forms(host: computer.host, realm: snapshot.realm,
                                              netbiosDomain: snapshot.netbiosDomain)
            guard !forms.isEmpty else { continue }
            guard let hash = hashes[computer.account.lowercased()], !hash.isEmpty else {
                out += "# \(computer.account): a machine account with no NT hash — the domain "
                out += "would not give it up, so machine authentication cannot work for it.\n\n"
                continue
            }
            guard forms.allSatisfy({ ConfigGenerator.quotedEntryName($0) != nil }) else {
                out += "# \(computer.account): left out — one of its identities cannot be "
                out += "written into a users file (a quote, a control character, or \"%{\").\n\n"
                continue
            }
            for form in forms {
                guard let line = RadiusAuthorize.ntPasswordLine(username: form, hashHex: hash) else { continue }
                out += line
                // `Sheep-OU` is the machine's container in the app's notation, which for the
                // usual `CN=Computers` is empty — a rule about machines names the group.
                out += identityCheckItems(ou: "", groups: [MachineIdentity.groupTag])
                out += "\n\n"
            }
        }
        return out
    }

    /// The rest of the user's **check** line: who they are, for the rules to test.
    ///
    /// Check items written with an assignment operator are not compared against the request —
    /// they are config items, and `rlm_files` puts them in `&control:`, exactly as it does for
    /// `Cleartext-Password`. Verified on 3.2.10: `Sheep-Group := "NetAdmins", Sheep-Group +=
    /// "Staff"` makes `&control:Sheep-Group[*] == "NetAdmins"` *and* `== "Staff"` true, and the
    /// user still matches normally. `:=` for the first value and `+=` after it is what makes
    /// the attribute multi-valued.
    ///
    /// These are always written, whether or not any rules exist: the cost is two lines in a
    /// file nobody reads by hand, and it means a rule starts working the moment it is added.
    static func identityCheckItems(for user: LabUser, groups: [LabGroup]) -> String {
        identityCheckItems(ou: user.effectiveOU, groups: groups.map(\.name))
    }

    /// The same two check items from plain strings, which is what a directory snapshot has.
    static func identityCheckItems(ou: String, groups: [String]) -> String {
        var out = ", \(SheepAttribute.ou) := \"\(quoted(ou))\""
        var emitted = 0
        for name in groups where !name.isEmpty {
            out += ", \(SheepAttribute.group) \(emitted == 0 ? ":=" : "+=") \"\(quoted(name))\""
            emitted += 1
        }
        return out
    }

    /// Escape for a double-quoted FreeRADIUS string.
    ///
    /// **`\n` is not decoration.** Every entry in the `users` file is one line, so a value
    /// carrying a newline ends the string in the middle and radiusd rejects the whole file
    /// with `Parse error (check) for entry …: Expected end of line or comma` — measured on
    /// 3.2.10. That is a fail-closed outcome, not an injected second account (the reopened
    /// quote never parses), but the consequence is that **nobody can authenticate at all**
    /// until the value is removed. `Validation` keeps newlines out of the seed table; the
    /// directory snapshot has no such gate, and LDAP and AD both allow them.
    ///
    /// **`%` is deliberately NOT escaped.** Measured against the real server: a bare `%` in
    /// this file is literal (an entry written `a%b` matches the password `a%b`, and `a%%b`
    /// does not), so escaping it would break every password containing a per-cent sign. Only
    /// `%{…}` is expanded, and it has no escape — `isSafeForAuthorize` refuses those instead.
    static func quoted(_ s: String) -> String {
        var out = ""
        for character in s {
            switch character {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            default: out.append(character)
            }
        }
        return out
    }

    /// May this value be written into the `users` file at all?
    ///
    /// `%{…}` is an xlat expansion and `rlm_files` performs it: an entry whose password reads
    /// `a%{User-Name}b` is matched against `a` + the name the supplicant sent + `b`, so the
    /// stored password is not the one checked. Measured on 3.2.10, and neither `%%{` nor `\%{`
    /// produces a literal — there is no escape. A name or password containing `%{` therefore
    /// cannot be represented, and the honest answer is to leave the account out and say so
    /// rather than write a line that means something else.
    ///
    /// Only reachable from the directory snapshot: `Validation.usernameAllowed` and
    /// `nameAllowed` already exclude `%`, `{` and `}` from anything typed into this app.
    static func isSafeForAuthorize(_ s: String) -> Bool { !s.contains("%{") }

    /// **An entry NAME in the `users` file, which is not quoted the way a value is**
    /// (build 24, measured on 3.2.10 with `radiusd -X`).
    ///
    /// `quoted(_:)` doubles a backslash, which is right for a value and **wrong for a name**:
    /// the `users` parser does not unescape `\\` in the entry name, so
    /// `"LABSHEEP\\PC$"` is an account literally called `LABSHEEP\\PC$` and the supplicant
    /// sending `LABSHEEP\PC$` matches nothing. Measured both ways against the real server:
    ///
    ///     "TESTSHEEP\RAW$"       → files: users: Matched entry TESTSHEEP\RAW$ at line 3
    ///                              Login OK / Login incorrect, as the password deserves
    ///     "TESTSHEEP\\ESCAPED$"  → no match at all
    ///                              Login incorrect (No Auth-Type found: rejecting the user)
    ///
    /// So a backslash is written **literally**. That is safe rather than lucky: taken
    /// literally it cannot end the string or start an escape, so there is nothing to inject
    /// with. A `"` would end the name and has no working escape either, and a newline, CR or
    /// tab would end the line — none of them can occur in a `sAMAccountName` or in a name this
    /// app will accept, so a name carrying one is refused (nil) rather than mangled.
    ///
    /// Only machine identities can contain a backslash: `DirectoryNames.problem` refuses one
    /// in anything a person types, so for a user this is `quoted(_:)` by another name.
    static func quotedEntryName(_ name: String) -> String? {
        guard !name.isEmpty, isSafeForAuthorize(name) else { return nil }
        guard !name.contains("\"") else { return nil }
        guard !name.unicodeScalars.contains(where: { $0.value < 0x20 || $0.value == 0x7F }) else { return nil }
        return name
    }

    // MARK: slapd

    /// `dataDir` is explicit because `rebuildLDAP` seeds a staging directory first and only
    /// swaps it in once slapadd has succeeded — the slapadd run and the live server therefore
    /// need the same config pointed at two different directories.
    /// The three files slapd needs for LDAPS and StartTLS.
    nonisolated struct TLSFiles: Sendable {
        let ca: String
        let certificate: String
        let key: String
    }

    static func slapdConf(base: String, schemaDir: String, dataDir: String, settings s: LabSettings,
                          adminHash: String, tls: TLSFiles? = nil) -> String {
        let tlsBlock = tls.map {
            """

            # LDAPS on its own port and StartTLS on the plain one, from the same files.
            # TLS 1.2 is the floor (3.3 is slapd's spelling); no client certificate is asked
            # for — this authenticates the *server* to the device, nothing more.
            TLSCACertificateFile "\($0.ca)"
            TLSCertificateFile "\($0.certificate)"
            TLSCertificateKeyFile "\($0.key)"
            TLSProtocolMin 3.3
            TLSVerifyClient never

            """
        } ?? ""
        return """
        # Generated by SheepRadius — edits are overwritten on Apply.
        include \(schemaDir)/core.schema
        include \(schemaDir)/cosine.schema
        include \(schemaDir)/inetorgperson.schema
        include \(schemaDir)/nis.schema
        include "\(base)/ldap/sheepradius.schema"

        pidfile "\(base)/run/slapd.pid"
        argsfile "\(base)/run/slapd.args"

        database ldif
        suffix "\(s.ldapSuffix)"
        directory "\(dataDir)"
        rootdn "\(s.ldapAdminDN)"
        rootpw \(adminHash)

        # Both password attributes are write-nobody, read-nobody: `auth` lets a bind be
        # checked against them and nothing else. Not even the owner can read or change their
        # own — the app's user table is the source of truth, and a password changed over LDAP
        # would be silently overwritten by the next Apply while RADIUS went on using the old
        # one. The rootdn bypasses ACLs, which is how a NAC bound as the admin DN reads the
        # NT hash.
        access to attrs=userPassword,sambaNTPassword by anonymous auth by * none
        access to * by * read

        # memberOf is seeded statically by slapadd; the overlay is what makes the attribute
        # itself known to the schema, and keeps it right for any later online change.
        overlay memberof
        memberof-group-oc groupOfNames
        memberof-member-ad member
        memberof-memberof-ad memberOf
        \(tlsBlock)
        """
    }

    /// The AD-shaped seed: nested OUs, users carrying `sAMAccountName` / `userPrincipalName` /
    /// `memberOf`, and a `groupOfNames` per group under `ou=groups`.
    ///
    /// `memberOf` is written **statically** rather than left to the memberof overlay, because
    /// the overlay only fires on writes through the frontend and this directory is built by
    /// slapadd. Verified on Apple's slapd: slapadd accepts the values and a later search
    /// returns them, including when `memberOf` is requested by name.
    ///
    /// `hash` is injected so tests are deterministic; production passes `ssha(_:)`.
    static func seedLDIF(users: [LabUser], groups: [LabGroup], ous: [String] = [],
                         settings s: LabSettings, hash: (String) -> String) -> String {
        let suffix = s.ldapSuffix
        let firstRDN = suffix.split(separator: ",").first.map(String.init) ?? "dc=lab"
        let dc = firstRDN.split(separator: "=").last.map(String.init) ?? "lab"
        let domain = s.dnsDomain
        func groupDN(_ name: String) -> String { "cn=\(name),ou=groups,\(suffix)" }

        // Every value goes through `LDIFValue` (build 20, audit N-5): a name, a display name
        // or a description that is non-ASCII, or that begins or ends with a space, has to be
        // written `attr:: <base64>` or the reader gets something other than what was meant.
        var out = LDIFValue.row("dn", suffix)
            + "objectClass: dcObject\nobjectClass: organization\n"
            + LDIFValue.row("dc", dc)
            + LDIFValue.row("o", "SheepRadius Lab")
            + "\n"
            + LDIFValue.row("dn", "ou=groups,\(suffix)")
            + "objectClass: organizationalUnit\n"
            + LDIFValue.row("ou", "groups")
            + "\n\n"
            + adminIdentityLDIF(settings: s)

        let active = users.filter { $0.enabled && !$0.username.isEmpty }

        // Every OU, parents before children, each emitted once. `ous` is the document's full
        // union (explicit OUs + every ancestor + the ones users sit in), so an OU with no
        // users is still a real container a device can browse into. The fallback keeps this
        // callable with just a user list.
        var wanted = ous
        if wanted.isEmpty {
            var byKey: [String: String] = [:]
            for u in active {
                for step in OUPath.selfAndAncestors(of: u.effectiveOU) where byKey[step.lowercased()] == nil {
                    byKey[step.lowercased()] = step
                }
            }
            wanted = byKey.values.sorted(by: OUPath.orderedBefore)
        }
        var emittedOUs = Set<String>()
        for path in wanted.sorted(by: OUPath.orderedBefore) {
            let segments = OUPath.segments(path)
            guard let leaf = segments.last else { continue }
            let dn = (segments.reversed().map { "ou=\($0)" } + [suffix]).joined(separator: ",")
            guard emittedOUs.insert(dn.lowercased()).inserted else { continue }
            out += LDIFValue.row("dn", dn) + "objectClass: organizationalUnit\n"
                + LDIFValue.row("ou", leaf) + "\n"
        }

        let byID = Dictionary(groups.map { ($0.id, $0) }, uniquingKeysWith: { first, _ in first })
        var members: [String: [String]] = [LabGroup.everyoneName: []]
        for group in groups where !group.name.isEmpty { members[group.name] = [] }

        for (n, u) in active.enumerated() {
            let dn = u.dn(base: suffix)
            let mine = u.groups.compactMap { byID[$0] }.filter { !$0.name.isEmpty }
            let display = u.displayName.isEmpty ? u.username : u.displayName
            let upn = domain.isEmpty ? u.username : "\(u.username)@\(domain)"

            out += LDIFValue.row("dn", dn)
            out += "objectClass: inetOrgPerson\nobjectClass: posixAccount\nobjectClass: sheepRadiusAccount\n"
            out += LDIFValue.row("uid", u.username)
            out += LDIFValue.row("cn", u.username)
            out += LDIFValue.row("sn", u.username)
            out += LDIFValue.row("displayName", display)
            out += LDIFValue.row("sAMAccountName", u.username)
            out += LDIFValue.row("userPrincipalName", upn)
            out += LDIFValue.row("mail", upn)
            out += "uidNumber: \(10001 + n)\ngidNumber: 10000\n"
            out += LDIFValue.row("homeDirectory", "/home/" + u.username)
            out += LDIFValue.row("userPassword", hash(u.password))
            // The NT hash a NAC reads to run PEAP-MSCHAPv2 from a generic-LDAP source
            // instead of joining a domain. Password-equivalent — see the ACL in slapdConf.
            if s.publishNTHashes {
                out += LDIFValue.row("sambaNTPassword", MD4.ntPasswordHash(u.password))
            }
            out += LDIFValue.row("memberOf", groupDN(LabGroup.everyoneName))
            members[LabGroup.everyoneName, default: []].append(dn)
            for group in mine {
                out += LDIFValue.row("memberOf", groupDN(group.name))
                members[group.name, default: []].append(dn)
            }
            out += "\n"
        }

        // netusers first (it is generated, not user-defined), then the rest in document order.
        let ordered = [LabGroup(name: LabGroup.everyoneName, description: "Every enabled lab user")]
            + groups.filter { !$0.name.isEmpty && $0.name != LabGroup.everyoneName }
        for group in ordered {
            out += LDIFValue.row("dn", groupDN(group.name))
            out += "objectClass: groupOfNames\n"
            out += LDIFValue.row("cn", group.name)
            if !group.description.isEmpty { out += LDIFValue.row("description", group.description) }
            let mine = members[group.name] ?? []
            // **The admin DN is always a member** (build 21), not only when the group would
            // otherwise be empty.
            //
            // `groupOfNames` requires at least one `member`: slapadd rejects an entry without
            // one, and slapd rejects the *modify* that would remove the last one. Until this
            // build the placeholder went in only for an empty group, so unticking the last
            // real member of a seeded group — alice out of NetAdmins, on a fresh lab — came
            // back as "Object class violation" with nothing a person could do about it. The
            // placeholder is a DN the parser drops on the way in (`DirectorySnapshotParser`
            // filters `member` to `uid=`), every device already knows to ignore it, and the
            // online `createGroup` has written it since build 17 — so this makes a seeded
            // group and a created one the same shape.
            out += LDIFValue.rows("member", [s.ldapAdminDN] + mine)
            out += "\n"
        }
        return out
    }

    /// **The two entries that make the admin DN resolve** (build 24).
    ///
    /// `rootdn` does not have to exist as an entry — slapd checks a bind against `rootpw` in
    /// the frontend, before any backend lookup — and until this build it did not, which is why
    /// `ldapsearch -b <base> "(cn=admin)"` came back empty on a directory whose own device
    /// table told you to bind as exactly that. A NAC that resolves the bind account before it
    /// uses it (and iMaster's synchronisation page does) had nothing to find.
    ///
    /// So the container and the account are written, and the container is **`cn=Users`**,
    /// where Active Directory keeps its own. `rootdn` / `rootpw` in slapd.conf stay the
    /// authority: `fe_op_bind` tries `be_isroot_pw` first and only falls through to the entry
    /// if that fails, so the entry deliberately carries **no `userPassword`** — one password
    /// for one account, and no second copy in the database to go stale when it is changed.
    ///
    /// **`organizationalRole`, not `organizationalUnit` or `inetOrgPerson`**, and both of
    /// those were tried:
    ///
    /// - `organizationalUnit` MUST have `ou` and the RDN here is `cn=`, so slapadd refuses the
    ///   entry outright (`naming attribute 'cn' is not present in entry`).
    /// - `inetOrgPerson` parses, but `OpenLDAPDirectoryCommands.readAll` filters on exactly
    ///   that class — the administrator would appear in the Users pane as an account with a
    ///   Delete beside it. `organizationalRole` matches neither that filter nor the
    ///   `organizationalUnit` one, so the panes and the OU tree are unchanged.
    ///
    /// There is no `container` class in OpenLDAP 2.7.1's core schema; `organizationalRole` is
    /// what the bundled `core.schema` gives a `cn=`-named node, and it carries `description`.
    static func adminIdentityLDIF(settings s: LabSettings) -> String {
        // A pinned DN is somebody's own spelling — it may not be under `cn=Users`, or under
        // this base DN at all — so nothing is invented for it. Only the default shape, which
        // this app owns end to end, gets its containers written.
        guard s.ldapAdminDN == LabSettings.defaultAdminDN(suffix: s.ldapSuffix) else { return "" }
        var out = LDIFValue.row("dn", s.ldapAdminContainerDN)
        out += "objectClass: organizationalRole\n"
        out += LDIFValue.row("cn", "Users")
        out += LDIFValue.row("description", "Directory accounts, as Active Directory names the container.")
        out += "\n"
        out += LDIFValue.row("dn", s.ldapAdminDN)
        out += "objectClass: organizationalRole\n"
        out += LDIFValue.row("cn", "Administrator")
        out += LDIFValue.row("description",
                             "The directory administrator. Its password is slapd's rootpw, "
                             + "set under Directory \u{25B8} Server.")
        out += "\n"
        return out
    }

    /// Two AD attributes plus an AUXILIARY class to hang them on. OIDs are Microsoft's real
    /// ones so a device configured for AD finds what it expects; the objectclass OID is in a
    /// private arc. Apple's slapd has no schema directory of its own to extend, so this file
    /// is written into the lab folder and `include`d from the generated slapd.conf.
    static let sheepSchema = """
    # Generated by SheepRadius — edits are overwritten on Apply.
    attributetype ( 1.2.840.113556.1.4.221
    \tNAME 'sAMAccountName'
    \tEQUALITY caseIgnoreMatch
    \tSUBSTR caseIgnoreSubstringsMatch
    \tSYNTAX 1.3.6.1.4.1.1466.115.121.1.15
    \tSINGLE-VALUE )

    attributetype ( 1.2.840.113556.1.4.656
    \tNAME 'userPrincipalName'
    \tEQUALITY caseIgnoreMatch
    \tSUBSTR caseIgnoreSubstringsMatch
    \tSYNTAX 1.3.6.1.4.1.1466.115.121.1.15
    \tSINGLE-VALUE )

    # Same definition samba.schema gives it. Declared here rather than including
    # samba.schema, because that file's sambaSamAccount makes sambaSID mandatory and we have
    # no SIDs to give out — the NAC only ever reads this one attribute.
    attributetype ( 1.3.6.1.4.1.7165.2.1.25
    \tNAME 'sambaNTPassword'
    \tDESC 'MD4 hash of the unicode password'
    \tEQUALITY caseIgnoreIA5Match
    \tSYNTAX 1.3.6.1.4.1.1466.115.121.1.26{32}
    \tSINGLE-VALUE )

    objectclass ( 1.3.6.1.4.1.99999.1.1
    \tNAME 'sheepRadiusAccount'
    \tDESC 'AD-style attributes for SheepRadius lab users'
    \tSUP top AUXILIARY
    \tMAY ( sAMAccountName $ userPrincipalName $ sambaNTPassword ) )

    """

    /// Apple's slapd build rejects cleartext userPassword/rootpw, so everything is {SSHA}.
    static func ssha(_ password: String, salt: Data? = nil) -> String {
        let salt = salt ?? Data((0..<8).map { _ in UInt8.random(in: .min ... .max) })
        let digest = Insecure.SHA1.hash(data: Data(password.utf8) + salt)
        return "{SSHA}" + (Data(digest) + salt).base64EncodedString()
    }

    // MARK: OpenSSL

    static let caExtensions = """
    [req]
    distinguished_name = dn
    x509_extensions = v3_ca
    prompt = no
    [dn]
    O = SheepRadius Lab
    CN = SheepRadius Test CA
    [v3_ca]
    basicConstraints = critical,CA:TRUE
    keyUsage = critical,keyCertSign,cRLSign
    subjectKeyIdentifier = hash

    """

    // MARK: LDAP server certificate

    /// The SAN for the LDAP leaf, in the order openssl emits it.
    ///
    /// Devices are usually pointed at an **IP**, and they do validate it, so every current
    /// non-loopback IPv4 goes in alongside the names. `localhost` is listed for other TLS
    /// clients even though OpenLDAP's own client rejects that particular name (see
    /// `ldapsHostNote`); 127.0.0.1 is what actually works there.
    static func ldapSANEntries(name: String, hostname: String, addresses: [String]) -> [String] {
        var out = ["DNS:\(name)"]
        let host = hostname.trimmingCharacters(in: .whitespaces)
        if !host.isEmpty, host != name, host != "localhost" { out.append("DNS:\(host)") }
        out.append("DNS:localhost")
        out.append("IP:127.0.0.1")
        // De-duplicated but order-stable, so an unchanged machine produces an identical SAN.
        var seen = Set(["127.0.0.1"])
        for address in addresses where seen.insert(address).inserted { out.append("IP:\(address)") }
        return out
    }

    static func ldapExtensions(name: String, hostname: String, addresses: [String]) -> String {
        """
        basicConstraints = CA:FALSE
        keyUsage = critical,digitalSignature,keyEncipherment
        extendedKeyUsage = serverAuth
        subjectAltName = \(ldapSANEntries(name: name, hostname: hostname, addresses: addresses).joined(separator: ","))

        """
    }

    /// The IP entries of a certificate's SAN, from `openssl x509 -noout -ext subjectAltName`:
    ///   `DNS:radius.lab.local, DNS:localhost, IP Address:127.0.0.1, IP Address:10.0.0.2`
    static func sanIPAddresses(in description: String) -> Set<String> {
        var out: Set<String> = []
        for piece in description.split(whereSeparator: { $0 == "," || $0 == "\n" }) {
            let token = piece.trimmingCharacters(in: .whitespaces)
            guard let range = token.range(of: "IP Address:") ?? token.range(of: "IP:") else { continue }
            out.insert(String(token[range.upperBound...]).trimmingCharacters(in: .whitespaces))
        }
        return out
    }

    /// The Mac's addresses change (new Wi-Fi network, a VPN comes up) far more often than
    /// anything else about this certificate, and a device validating the IP would start
    /// failing. Reissue only when an address is genuinely missing — never on every start.
    static func ldapCertificateNeedsReissue(sanDescription: String, addresses: [String]) -> Bool {
        let present = sanIPAddresses(in: sanDescription)
        return !Set(addresses).isSubset(of: present)
    }

    /// Why the Test pane and the docs say 127.0.0.1 rather than localhost.
    static let ldapsHostNote = "OpenLDAP's own client rejects the literal name \"localhost\" over TLS even when the certificate lists it; use 127.0.0.1, the Mac's IP, or its hostname."

    static func serverExtensions(name: String) -> String {
        """
        basicConstraints = CA:FALSE
        keyUsage = critical,digitalSignature,keyEncipherment
        extendedKeyUsage = serverAuth
        subjectAltName = DNS:\(name)

        """
    }
}
