import Foundation

// MARK: - The site-local dictionary

/// The attributes the app declares in `raddb/dictionary` so the generated unlang can see *who*
/// the authenticating user is. They exist only inside radiusd.
///
/// **3000–3999 is the range FreeRADIUS reserves for exactly this.** Its own
/// `dictionary.freeradius.internal` says `Range: 3000-3999 · Site-local attributes (see
/// raddb/dictionary) · Do NOT define attributes in this range!` and `Range: 65536- · Invalid.`
/// Measured on 3.2.10: `radiusd -CX` accepts 65536 without a murmur, so the range has to be
/// enforced here rather than left to the parser.
///
/// An attribute number above 255 **cannot be encoded into a RADIUS packet at all**, which is
/// what makes these structurally incapable of leaking onto the wire — not a filter that could
/// be forgotten. `raddb/dictionary` is read automatically; no `$INCLUDE` is needed.
nonisolated enum SheepAttribute {
    /// Every group the user belongs to, one value each, in membership order.
    static let group = "Sheep-Group"
    /// The user's OU path, `/`-separated (`Staff/IT`).
    static let ou = "Sheep-OU"
    /// One value per rule that matched — the app reads these back out of the debug stream.
    static let rule = "Sheep-Rule"
    /// Set on `&outer.session-state:` by the inner tunnel, so the outer post-auth knows the
    /// rules have already run with the real identity. See `RuleUnlang.postAuth`.
    static let handled = "Sheep-Handled"

    static let numbers: [(name: String, number: Int)] = [
        (group, 3000), (ou, 3001), (rule, 3002), (handled, 3003),
    ]

    /// Site-local range, as FreeRADIUS defines it.
    static let validRange = 3000...3999

    static var dictionary: String {
        var out = """
        # Generated by SheepRadius — edits are overwritten on Apply.
        #
        # Site-local attributes, in the 3000-3999 range FreeRADIUS reserves for this file.
        # They are how the Policy pane's rules know who is authenticating. Numbers above 255
        # cannot be encoded into a RADIUS packet, so none of these can reach the wire.

        """
        for item in numbers {
            out += "ATTRIBUTE\t\(item.name)\t\(item.number)\tstring\n"
        }
        return out
    }
}

// MARK: - The rule model

nonisolated enum RuleMatch: String, Codable, CaseIterable, Sendable {
    case all, any

    var label: String { self == .all ? "all of" : "any of" }
    /// How the generated conditions are joined. Each one is parenthesised already.
    var joiner: String { self == .all ? " && " : " || " }
}

nonisolated enum ConditionKind: String, Codable, CaseIterable, Sendable {
    case groupIs, groupIsNot
    case ouIs, ouIsUnder
    case usernameIs, usernameEndsWith, usernameMatches
    case nasIPIs, nasIPInCIDR, nasClient
    case nasIdentifierIs, nasIdentifierMatches
    case portType
    case ssid
    case calledStationIs, calledStationBeginsWith
    case callingMACIs, callingMACMatches
    case timeWindow
    case anyone
    /// **Build 24.** The identity is a domain-joined computer rather than a person — see
    /// `MachineIdentity`. It is a `groupIs` against a fixed name and is written as one; it
    /// exists as its own kind so the dropdown can say what it means without anybody having to
    /// know that the tag happens to be spelled "Domain Computers".
    case isComputerAccount
    case raw

    /// **All twenty-one, in four groups** (build 25, QA M-23).
    ///
    /// Build 13's flat list of fourteen was chosen to keep the dropdown short, and eight kinds
    /// were simply unreachable from it: `groupIsNot`, `ouIs`, `ouIsUnder`, `nasIPIs`,
    /// `nasIdentifierMatches`, `ssid`, `callingMACMatches` and `raw`. Every one of them
    /// decodes, generates and evaluates — they are tested in `unit.swift` and always have
    /// been — so the only thing missing was a way in. "User is not in group" and "User's OU
    /// is" are ordinary requests, and `raw` is the escape hatch a lab needs when nothing else
    /// fits.
    ///
    /// Twenty-one flat items is a menu nobody can read, so they are grouped by **what the
    /// condition is about**: the identity, where the request came from, what it came over,
    /// and everything else. The order inside each group is build 13's, so a person who knew
    /// where "User is" was still finds it in the same place.
    nonisolated struct Group: Sendable, Equatable, Identifiable {
        var title: String
        var kinds: [ConditionKind]
        var id: String { title }
    }

    static let groupedMenu: [Group] = [
        Group(title: "The account", kinds: [
            .groupIs, .groupIsNot, .ouIs, .ouIsUnder,
            .usernameIs, .usernameEndsWith, .usernameMatches, .isComputerAccount,
        ]),
        Group(title: "Where the request came from", kinds: [
            .nasClient, .nasIPIs, .nasIPInCIDR, .nasIdentifierIs, .nasIdentifierMatches,
        ]),
        Group(title: "What it came over", kinds: [
            .portType, .calledStationIs, .calledStationBeginsWith, .ssid,
            .callingMACIs, .callingMACMatches,
        ]),
        Group(title: "Anything else", kinds: [.timeWindow, .anyone, .raw]),
    ]

    /// Every kind the menu offers, flat — the list `menu(including:)` used to be, and the one
    /// the unit tests count against `allCases`.
    static let menu: [ConditionKind] = groupedMenu.flatMap(\.kinds)

    /// The menu plus `current`, when that is one of the kinds the menu leaves out. Nothing is
    /// left out any more, so this can only ever return `menu` — it stays because a kind added
    /// in a later build and forgotten here would otherwise make a rule unreadable.
    static func menu(including current: ConditionKind) -> [ConditionKind] {
        menu.contains(current) ? menu : menu + [current]
    }

    /// The grouped menu with `current` put back if it is somehow not in it.
    static func groupedMenu(including current: ConditionKind) -> [Group] {
        guard !menu.contains(current) else { return groupedMenu }
        return groupedMenu + [Group(title: "In this rule", kinds: [current])]
    }

    var label: String {
        switch self {
        case .groupIs: "User is in group"
        case .groupIsNot: "User is not in group"
        case .ouIs: "User's OU is"
        case .ouIsUnder: "User's OU is under"
        case .usernameIs: "User is"
        case .usernameEndsWith: "Username ends with"
        case .usernameMatches: "Username matches (regex)"
        case .nasIPIs: "NAS-IP is"
        case .nasIPInCIDR: "NAS-IP is / in subnet"
        case .nasClient: "From NAS client"
        case .nasIdentifierIs: "NAS-Identifier is"
        case .nasIdentifierMatches: "NAS-Identifier matches (regex)"
        case .portType: "Wired or Wi-Fi"
        case .ssid: "SSID (after the last colon) is"
        case .calledStationIs: "SSID / Called-Station-Id is"
        case .calledStationBeginsWith: "SSID / Called-Station-Id begins with"
        case .callingMACIs: "Device MAC is"
        case .callingMACMatches: "Device MAC matches (regex)"
        case .timeWindow: "Time window"
        case .anyone: "Anyone"
        case .isComputerAccount: "Identity is a computer account"
        case .raw: "Raw unlang condition"
        }
    }

    /// True when the condition depends only on the user table, so Users ▸ Properties can say
    /// whether a rule applies without inventing a request. Everything else "depends on the
    /// request". `anyone` is user-side because it is true for everybody.
    var isUserSide: Bool {
        switch self {
        case .groupIs, .groupIsNot, .ouIs, .ouIsUnder,
             .usernameIs, .usernameEndsWith, .usernameMatches, .anyone, .isComputerAccount: true
        default: false
        }
    }

    /// The condition takes no value at all.
    var isValueless: Bool { self == .anyone || self == .isComputerAccount }

    /// The value field is a free-text box unless this says otherwise.
    var picksGroup: Bool { self == .groupIs || self == .groupIsNot }
    var picksOU: Bool { self == .ouIs || self == .ouIsUnder }
    var picksClient: Bool { self == .nasClient }
    var picksPortType: Bool { self == .portType }
    var isTimeWindow: Bool { self == .timeWindow }
    var isRaw: Bool { self == .raw }

    var placeholder: String {
        switch self {
        case .usernameIs: "alice"
        case .usernameEndsWith: "@lab.local"
        case .usernameMatches, .nasIdentifierMatches: "^sw-"
        case .nasIPIs: "10.0.0.1"
        case .nasIPInCIDR: "10.0.0.0/24 or 10.0.0.1"
        case .nasIdentifierIs: "sw-lab-1"
        case .ssid: "Lab-Guest"
        case .calledStationIs: "SIAM-BUILDING:test2"
        case .calledStationBeginsWith: "SIAM-BUILDING:"
        case .callingMACIs: "aa:bb:cc:dd:ee:ff"
        case .callingMACMatches: "^aa:bb:cc"
        case .raw: "&Service-Type == Framed-User"
        default: ""
        }
    }

    var hint: String {
        switch self {
        case .groupIs, .groupIsNot:
            "Matched against &control:Sheep-Group, which raddb/authorize sets from this user's group list."
        case .ouIs:
            "Exactly this OU. Use \"OU is under\" to include everything below it."
        case .ouIsUnder:
            "This OU and every OU below it."
        case .usernameIs:
            "The whole User-Name, exactly. For PEAP and TTLS this is the identity inside the tunnel, not the anonymous outer one."
        case .usernameEndsWith:
            "The end of User-Name — a realm like @lab.local, or a suffix your naming scheme uses."
        case .usernameMatches:
            "A regular expression, matched against User-Name. For PEAP this is the identity inside the tunnel."
        case .nasIPIs, .nasIPInCIDR, .nasClient:
            "Matched against the NAS-IP-Address the device puts in the request — not the packet's source address. A single address or a CIDR both work."
        case .nasIdentifierIs, .nasIdentifierMatches:
            "NAS-Identifier is the name the switch or AP calls itself."
        case .portType:
            "NAS-Port-Type: Ethernet for a wired switch port, Wireless-802.11 for Wi-Fi."
        case .ssid:
            "Compares the part after the last colon of Called-Station-Id. That is the SSID only if the AP puts it there — \"<AP MAC>:<SSID>\" and \"<AP group>:<SSID>\" both work, but many vendors send something else entirely. Check the Log or the Test pane for what the access points actually send, and use \"Called-Station-Id is\" when you know the whole value."
        case .calledStationIs:
            "The whole Called-Station-Id, exactly as the AP sends it, compared case-sensitively — for example SIAM-BUILDING:test2."
        case .calledStationBeginsWith:
            "A prefix of Called-Station-Id, case-sensitive. \"SIAM-BUILDING:\" — with the colon — is every SSID on that AP group."
        case .callingMACIs:
            "The client's MAC. aa:bb:…, AA-BB-…, aabb.ccdd.eeff and aabbccddeeff all match, case-insensitively."
        case .callingMACMatches:
            "A regular expression, matched case-insensitively against Calling-Station-Id exactly as the NAS sent it."
        case .timeWindow:
            "Local time on this host. A window whose end is before its start wraps past midnight."
        case .anyone:
            "Matches every request. On the last rule that is a catch-all; anywhere else, nothing below it can ever run."
        case .isComputerAccount:
            "True for a domain-joined machine authenticating as itself — host/pc.lab.sheep, LABSHEEP\\PC$, PC$ and the other forms Windows sends. raddb/authorize tags every machine account with the group \"\(MachineIdentity.groupTag)\", and this compares against that tag. Samba AD only: OpenLDAP cannot be joined."
        case .raw:
            "unlang, written verbatim into the condition. Apply validates it with radiusd -CX."
        }
    }

    /// The condition in the fewest plain words, for an auto-generated rule name.
    /// `Group NetAdmins`, `User alice`, `Wi-Fi`. The value is filled in by `RuleCondition`.
    var nameLead: String {
        switch self {
        case .groupIs: "Group"
        case .groupIsNot: "Not in group"
        case .ouIs, .ouIsUnder: "OU"
        case .usernameIs: "User"
        case .usernameEndsWith: "Username ends"
        case .usernameMatches: "Username"
        case .nasIPIs, .nasIPInCIDR: "NAS-IP"
        case .nasClient: "Client"
        case .nasIdentifierIs, .nasIdentifierMatches: "NAS"
        case .portType: ""
        case .ssid: "SSID"
        case .calledStationIs: "Called-Station-Id"
        case .calledStationBeginsWith: "Called-Station-Id"
        case .callingMACIs, .callingMACMatches: "MAC"
        case .timeWindow: "Time"
        case .anyone: "Anyone"
        case .isComputerAccount: "Computer account"
        case .raw: "Condition"
        }
    }
}

/// The NAS-Port-Type values a lab actually uses. The names are the dictionary's own spellings
/// and go into the condition unquoted.
nonisolated enum RulePortType: String, Codable, CaseIterable, Sendable {
    case ethernet = "Ethernet"
    case wireless = "Wireless-802.11"
    case virtual = "Virtual"

    var label: String {
        switch self {
        case .ethernet: "Ethernet (wired)"
        case .wireless: "Wireless-802.11 (Wi-Fi)"
        case .virtual: "Virtual"
        }
    }

    /// For the "When" column and auto-generated names, where the dictionary spelling is noise.
    var shortLabel: String {
        switch self {
        case .ethernet: "Wired"
        case .wireless: "Wi-Fi"
        case .virtual: "Virtual port"
        }
    }
}

nonisolated struct RuleCondition: Codable, Identifiable, Hashable, Sendable {
    var id = UUID()
    var kind = ConditionKind.groupIs
    /// A `NASClient` id, for `nasClient` — clients live in `lab.json`, so an id is right there
    /// and a renamed client keeps its rule.
    ///
    /// **It used to carry a `LabGroup` id for the group conditions too** (builds 10–20), which
    /// stopped making sense in build 21: the groups are the *directory's* now, they have no
    /// `UUID` this app assigns, and the generated unlang has always compared
    /// `&control:Sheep-Group` by **name**. So a group condition keeps its group in `value`, and
    /// the only id that can still be here for one is the **unresolved** leftover of a lab whose
    /// old group table no longer has it — which is what `isDanglingGroup` reports and what the
    /// rule list marks rather than dropping. See `LabDocument.migrateGroupConditions`.
    var reference: UUID?
    /// Everything else: the group **name**, an OU path, a regex, an IP or CIDR, an SSID, a MAC,
    /// raw unlang.
    var value = ""
    /// `timeWindow` only: minutes past local midnight. `from == to` means "all day".
    var fromMinute = 8 * 60
    var toMinute = 18 * 60
    /// `timeWindow` only. 1 = Monday … 7 = Sunday; all seven means "any day" and the weekday
    /// test is left out of the generated condition entirely.
    var weekdays: [Int] = [1, 2, 3, 4, 5]

    enum CodingKeys: String, CodingKey { case id, kind, reference, value, fromMinute, toMinute, weekdays }

    init(id: UUID = UUID(), kind: ConditionKind = .groupIs, reference: UUID? = nil, value: String = "",
         fromMinute: Int = 8 * 60, toMinute: Int = 18 * 60, weekdays: [Int] = [1, 2, 3, 4, 5]) {
        self.id = id
        self.kind = kind
        self.reference = reference
        self.value = value
        self.fromMinute = fromMinute
        self.toMinute = toMinute
        self.weekdays = weekdays
    }

    init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        let d = RuleCondition()
        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        kind = try c.decodeIfPresent(ConditionKind.self, forKey: .kind) ?? d.kind
        reference = try c.decodeIfPresent(UUID.self, forKey: .reference)
        value = try c.decodeIfPresent(String.self, forKey: .value) ?? ""
        fromMinute = try c.decodeIfPresent(Int.self, forKey: .fromMinute) ?? d.fromMinute
        toMinute = try c.decodeIfPresent(Int.self, forKey: .toMinute) ?? d.toMinute
        weekdays = try c.decodeIfPresent([Int].self, forKey: .weekdays) ?? d.weekdays
    }

    /// A group condition whose group could not be found when the lab was upgraded: the old
    /// table no longer had the id the rule pointed at. Kept and shown rather than deleted —
    /// the rule may be the only record of what somebody meant.
    var isDanglingGroup: Bool {
        kind.picksGroup && value.trimmingCharacters(in: .whitespaces).isEmpty && reference != nil
    }

    /// Monday-first, de-duplicated, in order. Empty means the condition can never be true.
    var normalizedWeekdays: [Int] { Array(Set(weekdays.filter { (1...7).contains($0) })).sorted() }

    var isAllDay: Bool {
        let from = max(0, min(1439, fromMinute)), to = max(0, min(1439, toMinute))
        return from == to || (from == 0 && to == 1439)
    }

    var isAnyDay: Bool { normalizedWeekdays.count == 7 }

    /// The weekday lookup costs an extra `update control` line, so it is only emitted when a
    /// rule actually restricts the days.
    var needsWeekday: Bool { kind == .timeWindow && !isAnyDay && !normalizedWeekdays.isEmpty }

    /// The condition as one short phrase — the "When" column, and the first half of an
    /// auto-generated rule name. Ids are resolved through the context, so a renamed group
    /// reads correctly everywhere at once.
    func summary(context: PolicyContext) -> String {
        let value = self.value.trimmingCharacters(in: .whitespaces)
        switch kind {
        case .groupIs, .groupIsNot:
            if !value.isEmpty { return "\(kind.nameLead) \(value)" }
            return "\(kind.nameLead) \(isDanglingGroup ? "(group no longer exists)" : "(no group)")"
        case .nasClient:
            return "\(kind.nameLead) \(context.clientName(reference) ?? "(no client)")"
        case .portType:
            return RulePortType(rawValue: value)?.shortLabel ?? "(no port type)"
        case .anyone:
            return "Anyone"
        case .isComputerAccount:
            return "Computer account"
        case .timeWindow:
            var parts: [String] = []
            if !isAllDay { parts.append("\(RuleUnlang.clock(fromMinute))–\(RuleUnlang.clock(toMinute))") }
            if !isAnyDay {
                parts.append(normalizedWeekdays.map { RuleUnlang.weekdayAbbreviations[$0 - 1] }
                    .joined(separator: " "))
            }
            return parts.isEmpty ? "Any time" : "Time \(parts.joined(separator: " "))"
        case .calledStationBeginsWith:
            return "\(kind.nameLead) \(value.isEmpty ? "…" : value)…"
        case .usernameEndsWith:
            return "Username …\(value.isEmpty ? "…" : value)"
        default:
            let lead = kind.nameLead
            let shown = value.isEmpty ? "…" : value
            return lead.isEmpty ? shown : "\(lead) \(shown)"
        }
    }
}

/// One conditional policy: IF all/any of these THEN do this, and optionally stop.
nonisolated struct PolicyRule: Codable, Identifiable, Hashable, Sendable {
    var id = UUID()
    var name = ""
    var enabled = true
    var match = RuleMatch.all
    var conditions: [RuleCondition] = []
    /// First match wins, like an ACL — **on by default for a new rule**, which is the mental
    /// model this pane is built around.
    var stopAfterMatch = true

    // Actions. All of them are optional; a rule with none of them set is a legitimate
    // "no change (just stop)" that shields the rules below it.
    var vlan = ""
    var replyAttributes = ""
    var sessionTimeout = ""
    /// **Whether the two fields above are sent at all** (build 25, QA M-21).
    ///
    /// The editor's **Also send attributes** switch used to be pure view state, and turning it
    /// off cleared `replyAttributes` *and* `sessionTimeout` on the spot — no warning, nothing
    /// to undo, and a rule's attribute lines are typed by hand a dozen at a time. The switch
    /// is this flag now: turning it off stops the lines being generated, the editor says the
    /// text is being kept and will go at the next Apply, and turning it back on before then
    /// brings it back exactly as it was.
    ///
    /// Left unset — by an older `lab.json`, or by a caller building a rule in code — it is
    /// derived from whether there is anything to send, which is exactly what the editor's
    /// `sync()` computed before this flag existed. So a rule from build 24 behaves as it did,
    /// and **Add rule** still opens with the box unticked.
    var sendsAttributes = true

    /// The derived default: on when there is something to send.
    static func sends(replyAttributes: String, sessionTimeout: String) -> Bool {
        !replyAttributes.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            || !sessionTimeout.trimmingCharacters(in: .whitespaces).isEmpty
    }
    var rejects = false
    var rejectMessage = ""

    enum CodingKeys: String, CodingKey {
        case id, name, enabled, match, conditions, stopAfterMatch
        case vlan, replyAttributes, sessionTimeout, sendsAttributes, rejects, rejectMessage
    }

    init(id: UUID = UUID(), name: String = "", enabled: Bool = true, match: RuleMatch = .all,
         conditions: [RuleCondition] = [], stopAfterMatch: Bool = true, vlan: String = "",
         replyAttributes: String = "", sessionTimeout: String = "", sendsAttributes: Bool? = nil,
         rejects: Bool = false, rejectMessage: String = "") {
        self.id = id
        self.name = name
        self.enabled = enabled
        self.match = match
        self.conditions = conditions
        self.stopAfterMatch = stopAfterMatch
        self.vlan = vlan
        self.replyAttributes = replyAttributes
        self.sessionTimeout = sessionTimeout
        self.sendsAttributes = sendsAttributes
            ?? Self.sends(replyAttributes: replyAttributes, sessionTimeout: sessionTimeout)
        self.rejects = rejects
        self.rejectMessage = rejectMessage
    }

    init(from decoder: any Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        let d = PolicyRule()
        id = try c.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        name = try c.decodeIfPresent(String.self, forKey: .name) ?? ""
        enabled = try c.decodeIfPresent(Bool.self, forKey: .enabled) ?? d.enabled
        match = try c.decodeIfPresent(RuleMatch.self, forKey: .match) ?? d.match
        conditions = try c.decodeIfPresent([RuleCondition].self, forKey: .conditions) ?? []
        stopAfterMatch = try c.decodeIfPresent(Bool.self, forKey: .stopAfterMatch) ?? d.stopAfterMatch
        vlan = try c.decodeIfPresent(String.self, forKey: .vlan) ?? ""
        replyAttributes = try c.decodeIfPresent(String.self, forKey: .replyAttributes) ?? ""
        sessionTimeout = try c.decodeIfPresent(String.self, forKey: .sessionTimeout) ?? ""
        sendsAttributes = try c.decodeIfPresent(Bool.self, forKey: .sendsAttributes)
            ?? Self.sends(replyAttributes: replyAttributes, sessionTimeout: sessionTimeout)
        rejects = try c.decodeIfPresent(Bool.self, forKey: .rejects) ?? false
        rejectMessage = try c.decodeIfPresent(String.self, forKey: .rejectMessage) ?? ""
    }

    /// The name a matched rule is tagged with, so an unnamed rule is still identifiable.
    ///
    /// A name is optional (build 13): left empty, the rule is called after what it does —
    /// "Group NetAdmins → VLAN 10" — which is also the string `Sheep-Rule` carries and the one
    /// Status ▸ Recent authentications prints, so what the pane shows and what radiusd reports
    /// are the same words. `RuleUnlang` and `PolicyEvaluator` must be given the same context,
    /// or the tag and the prediction would differ by a group name.
    func displayName(index: Int, context: PolicyContext = PolicyContext()) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        if !trimmed.isEmpty { return trimmed }
        let generated = autoName(context: context)
        return generated.isEmpty ? "Rule \(index + 1)" : generated
    }

    /// "Group NetAdmins → VLAN 10". Empty when there is nothing to say (no conditions and no
    /// actions), which is when `displayName` falls back to the position.
    func autoName(context: PolicyContext) -> String {
        var when = conditions.map { $0.summary(context: context) }
        if when.isEmpty { when = ["Anyone"] }
        let joiner = match == .any ? " or " : " + "
        let head = when.joined(separator: joiner)
        guard !head.isEmpty else { return "" }
        return "\(head) → \(autoAction)"
    }

    /// The action in as few words as possible, for the generated name — which is also the
    /// string `Sheep-Rule` carries into the debug stream, so attribute **values** stay out of
    /// it: `Filter-Id = "netadmins"` in a tag would be quotes inside quotes for no gain.
    var autoAction: String {
        if rejects { return "Reject" }
        let vlan = self.vlan.trimmingCharacters(in: .whitespaces)
        if !vlan.isEmpty { return "VLAN \(vlan)" }
        var names = sentAttributes.map(\.name)
        if sendsAttributes, !sessionTimeout.trimmingCharacters(in: .whitespaces).isEmpty {
            names.append("Session-Timeout")
        }
        guard let first = names.first else { return "no change" }
        return names.count == 1 ? "send \(first)" : "send \(first) +\(names.count - 1)"
    }

    /// True when nothing about the reply changes — the rule exists only to stop the walk.
    var isNoChange: Bool {
        vlan.trimmingCharacters(in: .whitespaces).isEmpty
            && alsoSend.isEmpty
            && !rejects
    }

    /// The reply lines this rule will really send — empty when **Also send attributes** is
    /// off, whatever is still in the box (M-21).
    var sentAttributes: [ReplyAttribute] {
        sendsAttributes ? ReplyAttribute.parse(replyAttributes) : []
    }

    /// The text that is being kept but is no longer sent, counted for the editor's warning.
    var heldBackAttributeCount: Int {
        guard !sendsAttributes else { return 0 }
        var n = ReplyAttribute.parse(replyAttributes).count
        if !sessionTimeout.trimmingCharacters(in: .whitespaces).isEmpty { n += 1 }
        return n
    }

    var needsWeekday: Bool { conditions.contains { $0.needsWeekday } }

    /// "VLAN 99 · Filter-Id = \"x\"" — what the rule does, for the row and for the auto name.
    /// "stop" is not mentioned: every rule stops now, so saying so on all of them says nothing.
    var actionSummary: String {
        var parts: [String] = []
        // Deliberately not the Reply-Message: this string becomes the rule's auto-generated
        // name and therefore the `Sheep-Rule` tag, and a sentence of prose does not belong in
        // a RADIUS attribute the Log pane prints on every match.
        if rejects { return "Reject" }
        if !vlan.trimmingCharacters(in: .whitespaces).isEmpty { parts.append("VLAN \(vlan)") }
        parts += alsoSend
        if parts.isEmpty { parts.append("no change") }
        return parts.joined(separator: " · ")
    }

    /// The reply lines besides the VLAN — the "Also send" column. `sessionTimeout` is a build-10
    /// field kept only so an old document still generates what it did; new rules write
    /// `Session-Timeout := …` as an ordinary attribute line.
    var alsoSend: [String] {
        guard sendsAttributes else { return [] }
        var out = ReplyAttribute.parse(replyAttributes).map(\.line)
        let timeout = sessionTimeout.trimmingCharacters(in: .whitespaces)
        if !timeout.isEmpty { out.append("Session-Timeout := \(timeout)") }
        return out
    }
}

/// What the generator and the evaluator need beyond the rule itself: the tables a condition
/// can point into.
nonisolated struct PolicyContext: Sendable {
    var clients: [NASClient] = []

    init(clients: [NASClient] = []) {
        self.clients = clients
    }

    init(_ doc: LabDocument) {
        clients = doc.clients
    }

    func clientAddress(_ id: UUID?) -> String? {
        guard let id, let client = clients.first(where: { $0.id == id }), !client.address.isEmpty else { return nil }
        return client.address
    }

    func clientName(_ id: UUID?) -> String? {
        guard let id, let client = clients.first(where: { $0.id == id }) else { return nil }
        return client.name.isEmpty ? client.address : client.name
    }
}

// MARK: - Migrating build 12's static reply

/// Build 12 kept the reply in two places: a VLAN and reply attributes on every **group**, and
/// an override of the same two on every **user**. Build 13 keeps it in one ordered rule list.
/// This turns the first into the second **without changing a single reply**, once, while an old
/// lab.json is being decoded — after which the old keys are gone for good.
///
/// What build 12 actually did, which is what has to be reproduced:
///
///   - VLAN: the user's own if set, otherwise the first of **their** groups that had one, in
///     the order that user's membership list happened to be in.
///   - attributes: the user's own lines first, then the lines of **every** group they belong
///     to, de-duplicated by attribute name with the first occurrence winning.
///
/// The rules it writes are, in order:
///
///   1. one rule per user whose reply the group rules below would not reproduce exactly —
///      anyone who had an override, and anyone whose groups merged into something no single
///      group rule can say. It carries that user's **whole** build-12 reply and stops.
///   2. one rule per group that had a VLAN or attributes, in the group list's order, each
///      carrying that group's whole reply and stopping. First match wins, so a user in two of
///      them gets the higher one — the same group that used to supply the VLAN.
///   3. whatever conditional rules the document already had, untouched, after those.
///
/// Step 1 is what makes the result exact rather than nearly exact, and `identical(…)` is the
/// check the unit tests run over every user of a fixture lab.
nonisolated enum PolicyMigration {
    /// The two build-12 keys of one user or one group.
    nonisolated struct Legacy: Sendable, Equatable {
        var vlan = ""
        var replyAttributes = ""

        init(vlan: String = "", replyAttributes: String = "") {
            self.vlan = vlan
            self.replyAttributes = replyAttributes
        }

        /// De-duplicated by attribute name, because that is what build 12 put in the file: the
        /// static reply kept the **first** line of a name and dropped the rest, within a group
        /// as much as across them.
        var lines: [String] {
            var seen = Set<String>()
            return ReplyAttribute.parse(replyAttributes)
                .filter { seen.insert($0.name).inserted }
                .map(\.line)
        }

        var isEmpty: Bool { vlan.trimmingCharacters(in: .whitespaces).isEmpty && lines.isEmpty }
    }

    /// A resolved reply: the VLAN and the attribute lines, in order. Two of these being equal
    /// is exactly what "the reply did not change" means.
    nonisolated struct Reply: Sendable, Equatable {
        var vlan = ""
        var lines: [String] = []

        var isEmpty: Bool { vlan.isEmpty && lines.isEmpty }
    }

    /// `ConfigGenerator.effectiveReply` as build 12 computed it, kept here because the type it
    /// used no longer exists.
    static func legacyReply(user: Legacy, groups: [Legacy]) -> Reply {
        var out = Reply()
        let own = user.vlan.trimmingCharacters(in: .whitespaces)
        out.vlan = own.isEmpty
            ? (groups.first { !$0.vlan.trimmingCharacters(in: .whitespaces).isEmpty }?.vlan ?? "")
            : own
        var seen = Set<String>()
        for attribute in ReplyAttribute.parse(user.replyAttributes)
        where seen.insert(attribute.name).inserted {
            out.lines.append(attribute.line)
        }
        for group in groups {
            for attribute in ReplyAttribute.parse(group.replyAttributes)
            where seen.insert(attribute.name).inserted {
                out.lines.append(attribute.line)
            }
        }
        return out
    }

    /// What the migrated **group** rules give a user: the first one that matches, which stops.
    static func groupRuleReply(memberOf: [UUID], order: [(id: UUID, legacy: Legacy)]) -> Reply {
        for entry in order where memberOf.contains(entry.id) && !entry.legacy.isEmpty {
            return Reply(vlan: entry.legacy.vlan.trimmingCharacters(in: .whitespaces),
                         lines: entry.legacy.lines)
        }
        return Reply()
    }

    static func migrate(users: [LabUser], groups: [LabGroup],
                        legacyUsers: [UUID: Legacy], legacyGroups: [UUID: Legacy],
                        existing: [PolicyRule]) -> [PolicyRule] {
        guard !legacyUsers.isEmpty || !legacyGroups.isEmpty else { return existing }
        let order = groups.map { (id: $0.id, name: $0.name, legacy: legacyGroups[$0.id] ?? Legacy()) }

        var pins: [PolicyRule] = []
        for user in users where !user.username.isEmpty {
            // The user's own groups **in their membership order** — that is the order build 12
            // resolved a VLAN in, and it is not necessarily the group list's order.
            let mine = user.groups.compactMap { id in order.first { $0.id == id }?.legacy }
            let before = legacyReply(user: legacyUsers[user.id] ?? Legacy(), groups: mine)
            let after = groupRuleReply(memberOf: user.groups,
                                       order: order.map { (id: $0.id, legacy: $0.legacy) })
            guard before != after else { continue }
            pins.append(rule(matching: RuleCondition(kind: .usernameIs, value: user.username),
                             reply: before))
        }

        var groupRules: [PolicyRule] = []
        for entry in order where !entry.legacy.isEmpty {
            groupRules.append(rule(matching: RuleCondition(kind: .groupIs, value: entry.name),
                                   reply: Reply(vlan: entry.legacy.vlan.trimmingCharacters(in: .whitespaces),
                                                lines: entry.legacy.lines)))
        }
        return pins + groupRules + existing
    }

    private static func rule(matching condition: RuleCondition, reply: Reply) -> PolicyRule {
        // Unnamed on purpose: the name is generated from the condition and the action, so it
        // follows a renamed group and reads like the list it is now part of.
        PolicyRule(conditions: [condition], stopAfterMatch: true,
                   vlan: reply.vlan, replyAttributes: reply.lines.joined(separator: "\n"))
    }

    /// What the migrated rules actually reply with, resolved by the evaluator — the same
    /// evaluator the live suite proves against radiusd.
    static func migratedReply(for user: LabUser, groups: [LabGroup], rules: [PolicyRule],
                              context: PolicyContext) -> Reply {
        let result = PolicyEvaluator.evaluate(user: user, groups: groups, rules: rules,
                                              context: context, request: PolicyRequest())
        var out = Reply()
        for line in result.lines {
            switch line.name {
            case "Tunnel-Private-Group-Id":
                out.vlan = line.value.trimmingCharacters(in: CharacterSet(charactersIn: "\""))
            case "Tunnel-Type", "Tunnel-Medium-Type":
                continue
            default:
                out.lines.append(line.line)
            }
        }
        return out
    }

    /// The proof, one complaint per user whose reply moved. Empty means the migration changed
    /// nothing at all. Used by the unit tests over a build-12 fixture, and by nothing else.
    static func differences(users: [LabUser], groups: [LabGroup],
                            legacyUsers: [UUID: Legacy], legacyGroups: [UUID: Legacy],
                            migrated: [PolicyRule], context: PolicyContext) -> [String] {
        var complaints: [String] = []
        for user in users where !user.username.isEmpty {
            let mine = user.groups
                .filter { id in groups.contains { $0.id == id } }
                .map { legacyGroups[$0] ?? Legacy() }
            let before = legacyReply(user: legacyUsers[user.id] ?? Legacy(), groups: mine)
            let after = migratedReply(for: user, groups: user.groups.compactMap { id in
                groups.first { $0.id == id }
            }, rules: migrated, context: context)
            if before != after { complaints.append("\(user.username): was \(before), now \(after)") }
        }
        return complaints
    }
}

/// The request-side facts a rule can test. Everything here comes from the RADIUS request, so
/// the Preview strip asks for them and the evaluator needs them to answer.
nonisolated struct PolicyRequest: Sendable, Hashable {
    var nasIPAddress = ""
    var nasIdentifier = ""
    var nasPortType = ""
    var calledStationID = ""
    var callingStationID = ""
    /// When the request happens, in this Mac's own time zone — that is what `%H%G` and the
    /// weekday lookup use inside radiusd.
    var date = Date()

    init(nasIPAddress: String = "", nasIdentifier: String = "", nasPortType: String = "",
         calledStationID: String = "", callingStationID: String = "", date: Date = Date()) {
        self.nasIPAddress = nasIPAddress
        self.nasIdentifier = nasIdentifier
        self.nasPortType = nasPortType
        self.calledStationID = calledStationID
        self.callingStationID = callingStationID
        self.date = date
    }
}

// MARK: - Generating the unlang
//
// `RuleUnlang` writes the configuration and `PolicyEvaluator` predicts it. They are in one
// file on purpose: every condition has to be expressed twice, and the only defence against
// the two drifting apart is that they sit next to each other and are tested against the real
// radiusd by the live suite's equivalence matrix.

nonisolated enum RuleUnlang {
    /// The rlm_date instance whose `%a` gives the local weekday. rlm_date is bundled for this
    /// one purpose: measured on 3.2.10, neither `&Current-Time` nor `&Time-Of-Day` is ever
    /// true in an unlang condition (they are paircompare virtuals, usable only in the users
    /// file), and no `%` expansion yields a weekday.
    static let weekdayModule = "sheep_weekday"
    /// A date/integer attribute to hand the module: its xlat takes an attribute name, not a
    /// literal, so the epoch has to be parked somewhere first.
    static let weekdayHolder = "Tmp-Integer-0"
    /// The rlm_always instance a Reject action calls. A bare `reject` is **not** an unlang
    /// keyword in 3.2 — it fails with `Failed to find "reject" as a module or policy`.
    static let rejectModule = "reject"

    /// strftime `%a` in the C locale, which is what radiusd renders regardless of the Mac's
    /// language (verified on a Thai-locale Mac: it prints `Fri`, not a localised abbreviation).
    static let weekdayAbbreviations = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

    static let weekdayNames = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

    /// A condition that is never true, for a rule whose condition cannot be expressed. Written
    /// rather than omitted, so a broken rule fails closed instead of matching everything.
    static let never = "(\"0\" == \"1\")"

    // MARK: Escaping

    /// Everything that could end a `#` comment line, flattened to a space. Used for every
    /// human-readable string this generator writes into a comment.
    static func oneLine(_ s: String) -> String {
        String(s.map { $0 == "\n" || $0 == "\r" ? " " : $0 })
    }

    /// A double-quoted unlang string.
    ///
    /// `%` is the one that bites: `"100% sure"` is a parse error (`Invalid variable expansion`)
    /// and `%%` is the escape. `${…}` is expanded by the *configuration* parser before unlang
    /// ever sees it and has no escape at all, which is why `Validation` refuses it in a rule.
    /// A newline would end the line and smuggle in a second directive.
    static func quoted(_ s: String) -> String {
        var out = ""
        for character in s {
            switch character {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "%": out += "%%"
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            default: out.append(character)
            }
        }
        return out
    }

    /// A `/…/`-delimited regular expression. The delimiter and `%` need escaping; everything
    /// else is the author's regex and is left exactly as typed.
    static func regexBody(_ s: String) -> String {
        var out = ""
        for character in s {
            switch character {
            case "/": out += "\\/"
            case "%": out += "%%"
            case "\n", "\r": break              // a newline cannot survive in a config line
            default: out.append(character)
            }
        }
        return out
    }

    /// Escape a literal so it can go inside a regex the app builds itself.
    static func regexLiteral(_ s: String) -> String {
        var out = ""
        for character in s {
            if "\\^$.|?*+()[]{}/".contains(character) { out.append("\\") }
            if character == "%" { out += "%%"; continue }
            out.append(character)
        }
        return out
    }

    // MARK: MAC addresses

    /// The 12 hex digits of a MAC, whatever shape it arrived in, or nil.
    ///
    /// Real kit sends all four of `aa:bb:cc:dd:ee:ff` (most APs), `AA-BB-CC-DD-EE-FF`
    /// (Microsoft / many switches), `aabb.ccdd.eeff` (Cisco IOS) and `aabbccddeeff`.
    static func macDigits(_ raw: String) -> String? {
        let digits = raw.lowercased().filter { $0.isHexDigit }
        let separators = raw.filter { !$0.isHexDigit }
        guard digits.count == 12, separators.allSatisfy({ ":-. ".contains($0) }) else { return nil }
        return digits
    }

    /// `aa[-:.]?bb[-:.]?cc[-:.]?dd[-:.]?ee[-:.]?ff` — an optional separator between every pair
    /// of digits, which is what makes one comparison form cover all four spellings. Verified
    /// against the real regex engine for colon, dash, Cisco dotted and bare.
    static func macRegex(_ digits: String) -> String {
        stride(from: 0, to: 12, by: 2)
            .map { String(digits.dropFirst($0).prefix(2)) }
            .joined(separator: "[-:.]?")
    }

    // MARK: Conditions

    /// **Comparing an attribute that is not in the request is an error in unlang, not false —
    /// and an error poisons the whole `||`.** Measured on 3.2.10 and the one thing that
    /// silently broke the first version of this generator:
    ///
    ///   - `(&Calling-Station-Id =~ /…/)` alone matches.
    ///   - `(&NAS-Identifier == "x") || (&Calling-Station-Id =~ /…/)` does **not** match a
    ///     request with no NAS-Identifier, even though the second half is true.
    ///   - reversing the two makes it match again, because `||` short-circuits.
    ///   - `!(&control:Sheep-Group[*] == "Guests")` is **false** for a user with no groups,
    ///     which is the opposite of what "group is not Guests" has to mean.
    ///
    /// So every comparison is paired with an existence test. Verified: the terse
    /// `(&Attr && &Attr == "x")` and `(!&Attr || !(&Attr == "x"))` both parse and behave.
    static func guarded(_ attribute: String, _ test: String) -> String {
        "(\(attribute) && \(test))"
    }

    /// The negated form: absent counts as "not equal", which is what a person means.
    static func refuted(_ attribute: String, _ test: String) -> String {
        "(!\(attribute) || !(\(test)))"
    }

    /// One condition, already parenthesised, or nil when it cannot be expressed.
    static func condition(_ c: RuleCondition, context: PolicyContext) -> String? {
        let value = c.value.trimmingCharacters(in: .whitespaces)
        let groupAttribute = "&control:\(SheepAttribute.group)"
        let ouAttribute = "&control:\(SheepAttribute.ou)"
        switch c.kind {
        case .groupIs:
            let name = value
            guard !name.isEmpty else { return nil }
            return guarded(groupAttribute, "\(groupAttribute)[*] == \"\(quoted(name))\"")
        case .groupIsNot:
            let name = value
            guard !name.isEmpty else { return nil }
            // `!(… [*] == x)` and not `[*] != x`: the latter asks whether *some* value differs,
            // which is true for a user who is in two groups, one of which is x.
            return refuted(groupAttribute, "\(groupAttribute)[*] == \"\(quoted(name))\"")
        case .ouIs:
            let path = OUPath.normalized(value)
            guard !path.isEmpty else { return nil }
            return guarded(ouAttribute, "\(ouAttribute) == \"\(quoted(path))\"")
        case .ouIsUnder:
            let path = OUPath.normalized(value)
            guard !path.isEmpty else { return nil }
            return guarded(ouAttribute, "\(ouAttribute) =~ /^\(regexLiteral(path))(\\/|$)/")
        case .usernameIs:
            guard !value.isEmpty else { return nil }
            return guarded("&User-Name", "&User-Name == \"\(quoted(value))\"")
        case .usernameEndsWith:
            guard !value.isEmpty else { return nil }
            return guarded("&User-Name", "&User-Name =~ /\(regexLiteral(value))$/")
        case .usernameMatches:
            guard !value.isEmpty else { return nil }
            return guarded("&User-Name", "&User-Name =~ /\(regexBody(value))/")
        case .nasIPIs:
            guard Validation.isValidAddress(value), !value.contains("/") else { return nil }
            return addressCondition(value)
        case .nasIPInCIDR:
            guard Validation.isValidAddress(value) else { return nil }
            return addressCondition(value)
        case .nasClient:
            guard let address = context.clientAddress(c.reference), Validation.isValidAddress(address) else { return nil }
            return addressCondition(address)
        case .nasIdentifierIs:
            guard !value.isEmpty else { return nil }
            return guarded("&NAS-Identifier", "&NAS-Identifier == \"\(quoted(value))\"")
        case .nasIdentifierMatches:
            guard !value.isEmpty else { return nil }
            return guarded("&NAS-Identifier", "&NAS-Identifier =~ /\(regexBody(value))/")
        case .portType:
            guard let type = RulePortType(rawValue: value) else { return nil }
            return guarded("&NAS-Port-Type", "&NAS-Port-Type == \(type.rawValue)")
        case .ssid:
            guard !value.isEmpty else { return nil }
            // Called-Station-Id is conventionally "<something>:<SSID>" — the AP's MAC on most
            // kit, the AP *group* on others — so this anchors on the colon and the end.
            return guarded("&Called-Station-Id", "&Called-Station-Id =~ /:\(regexLiteral(value))$/")
        case .calledStationIs:
            guard !value.isEmpty else { return nil }
            return guarded("&Called-Station-Id", "&Called-Station-Id == \"\(quoted(value))\"")
        case .calledStationBeginsWith:
            // `^` + the escaped literal, which is exactly what radctl's `begins` operator
            // writes; "SIAM-BUILDING:" therefore means every SSID in that AP group.
            guard !value.isEmpty else { return nil }
            return guarded("&Called-Station-Id", "&Called-Station-Id =~ /^\(regexLiteral(value))/")
        case .callingMACIs:
            guard let digits = macDigits(value) else { return nil }
            return guarded("&Calling-Station-Id", "&Calling-Station-Id =~ /^\(macRegex(digits))$/i")
        case .callingMACMatches:
            guard !value.isEmpty else { return nil }
            return guarded("&Calling-Station-Id", "&Calling-Station-Id =~ /\(regexBody(value))/i")
        case .timeWindow:
            return timeCondition(c)
        case .anyone:
            return "(true)"
        case .isComputerAccount:
            // Exactly a `groupIs` against the tag `ConfigGenerator.machineEntries` writes, so
            // there is one comparison in the generator rather than a second mechanism that
            // could disagree with it.
            return guarded(groupAttribute,
                           "\(groupAttribute)[*] == \"\(quoted(MachineIdentity.groupTag))\"")
        case .raw:
            guard !value.isEmpty else { return nil }
            return "(\(value.replacingOccurrences(of: "\n", with: " ")))"
        }
    }

    /// **`<`, not `==`, for a CIDR.** Measured on 3.2.10: `&NAS-IP-Address == 127.0.0.0/8` is
    /// never true, while `&NAS-IP-Address < 127.0.0.0/8` is the prefix-containment test. A
    /// single address uses `==`.
    private static func addressCondition(_ address: String) -> String {
        let operation = address.contains("/") ? "<" : "=="
        return guarded("&NAS-IP-Address", "&NAS-IP-Address \(operation) \(address)")
    }

    static func hhmm(_ minutes: Int) -> String {
        let clamped = max(0, min(1439, minutes))
        return String(format: "%02d%02d", clamped / 60, clamped % 60)
    }

    /// The same minute, as a person writes it: `08:00`.
    static func clock(_ minutes: Int) -> String {
        let text = hhmm(minutes)
        return "\(text.prefix(2)):\(text.suffix(2))"
    }

    /// `%H` and `%G` are the hour and minute of the request in **local** time, zero padded, so
    /// comparing `"%H%G"` as a string orders correctly. `&Current-Time` looks like the right
    /// answer and is not: it parses and is never true.
    static func timeCondition(_ c: RuleCondition) -> String? {
        let days = c.normalizedWeekdays
        guard !days.isEmpty else { return never }
        var parts: [String] = []
        if !c.isAllDay {
            let from = hhmm(c.fromMinute), to = hhmm(c.toMinute)
            if c.fromMinute <= c.toMinute {
                parts.append("(\"%H%G\" >= \"\(from)\" && \"%H%G\" <= \"\(to)\")")
            } else {
                // A window that ends before it starts runs through midnight.
                parts.append("(\"%H%G\" >= \"\(from)\" || \"%H%G\" <= \"\(to)\")")
            }
        }
        if days.count < 7 {
            let names = days.map { weekdayAbbreviations[$0 - 1] }.joined(separator: "|")
            parts.append("(\"%{\(weekdayModule):&control:\(weekdayHolder)}\" =~ /^(\(names))$/)")
        }
        guard !parts.isEmpty else { return "(true)" }
        return parts.count == 1 ? parts[0] : "(" + parts.joined(separator: " && ") + ")"
    }

    /// The whole IF of one rule. A rule with no conditions matches everything, which is
    /// written out as `(true)` rather than left implicit.
    static func conditions(_ rule: PolicyRule, context: PolicyContext) -> String {
        let parts = rule.conditions.map { condition($0, context: context) ?? never }
        guard !parts.isEmpty else { return "(true)" }
        // Every part is parenthesised, and so is the join: radiusd's parser copes without the
        // outer pair, but `if (a) && (b) {` is not a thing anyone should have to read.
        return parts.count == 1 ? parts[0] : "(" + parts.joined(separator: rule.match.joiner) + ")"
    }

    // MARK: Actions

    static func actions(_ rule: PolicyRule, index: Int, indent: String,
                        context: PolicyContext = PolicyContext()) -> String {
        var out = ""
        // Every match is tagged so the app can report it. `Sheep-Rule` is only ever written
        // inside an `update control` block and never appears in a generated condition, which
        // is what makes the debug line unambiguous to parse.
        out += "\(indent)update control {\n"
        out += "\(indent)\t\(SheepAttribute.rule) += \"\(quoted(rule.displayName(index: index, context: context)))\"\n"
        out += "\(indent)}\n"

        var replyLines: [String] = []
        let vlan = rule.vlan.trimmingCharacters(in: .whitespaces)
        if !vlan.isEmpty {
            // `:=` on all three, so a VLAN from a group reply is replaced rather than joined.
            replyLines += ["Tunnel-Type := VLAN", "Tunnel-Medium-Type := IEEE-802",
                           "Tunnel-Private-Group-Id := \"\(quoted(vlan))\""]
        }
        for attribute in rule.sentAttributes {
            replyLines.append(attribute.line)
        }
        let timeout = rule.sessionTimeout.trimmingCharacters(in: .whitespaces)
        if rule.sendsAttributes, !timeout.isEmpty, Int(timeout) != nil {
            replyLines.append("Session-Timeout := \(timeout)")
        }
        let message = rule.rejectMessage.trimmingCharacters(in: .whitespaces)
        if rule.rejects, !message.isEmpty {
            replyLines.append("Reply-Message := \"\(quoted(message))\"")
        }
        if !replyLines.isEmpty {
            out += "\(indent)update reply {\n"
            for line in replyLines { out += "\(indent)\t\(line)\n" }
            out += "\(indent)}\n"
        }
        if rule.rejects {
            out += "\(indent)\(rejectModule)\n"
        }
        return out
    }

    // MARK: The rule walk

    /// Rules, top to bottom, with "stop after match" expressed as `elsif` / `else` nesting.
    ///
    /// There is no `break` in a post-auth section, so first-match-wins is structural: a rule
    /// that stops puts everything after it in its `else`. When every rule stops — the default —
    /// that collapses into a plain `if / elsif / elsif` chain, which is exactly how an ACL
    /// reads. 30 levels of nesting were checked against the real parser for the mixed case.
    static func walk(_ rules: ArraySlice<PolicyRule>, context: PolicyContext, indent: String,
                     startIndex: Int, leadingElse: Bool = false) -> String {
        guard let rule = rules.first else { return "" }
        let rest = rules.dropFirst()
        let keyword = leadingElse ? "elsif" : "if"
        // **The one place a user-controlled string reaches unlang unescaped.** A `#` comment
        // ends at the newline, so a rule name or a condition value carrying one continues as
        // unlang — `radiusd -CX` accepts the result, so the staged parse does not catch it.
        // `RuleCondition.summary` trims `.whitespaces`, which is spaces and tabs only.
        var out = "\(indent)# \(startIndex + 1). \(oneLine(rule.displayName(index: startIndex, context: context)))"
        out += rule.stopAfterMatch ? "  (first match wins — nothing below runs)\n" : "  (keep going)\n"
        out += "\(indent)\(keyword) \(conditions(rule, context: context)) {\n"
        out += actions(rule, index: startIndex, indent: indent + "\t", context: context)
        out += "\(indent)}\n"
        guard !rest.isEmpty else { return out }

        if rule.stopAfterMatch {
            // An `elsif` chain is only equivalent when every rule in the tail also stops
            // (the last one's flag cannot matter — nothing follows it).
            if rest.dropLast().allSatisfy({ $0.stopAfterMatch }) {
                return out + walk(rest, context: context, indent: indent,
                                  startIndex: startIndex + 1, leadingElse: true)
            }
            out += "\(indent)else {\n"
            out += walk(rest, context: context, indent: indent + "\t", startIndex: startIndex + 1)
            out += "\(indent)}\n"
            return out
        }
        return out + walk(rest, context: context, indent: indent, startIndex: startIndex + 1)
    }

    /// The `post-auth` body for one virtual server.
    ///
    /// `inner` selects the inner-tunnel copy. See the comment block it writes for why there
    /// are two and how they avoid running twice.
    static func postAuth(rules: [PolicyRule], context: PolicyContext, customUnlang: String,
                         indent i: String, inner: Bool) -> String {
        let active = rules.filter { $0.enabled }
        var out = ""
        let custom = customUnlang.trimmingCharacters(in: .whitespacesAndNewlines)
        // Nothing to run means nothing to write: a lab with no rules generates the same empty
        // post-auth sections it always did, flag and all.
        if active.isEmpty, custom.isEmpty { return "" }

        if inner {
            out += """
            \(i)\t# PEAP / TTLS: this is the only place the real identity exists, and
            \(i)\t# copy_request_to_tunnel = yes puts the NAS attributes here too. The flag
            \(i)\t# tells the outer post-auth the rules have already run, so they do not run
            \(i)\t# a second time against an anonymous outer User-Name. use_tunneled_reply
            \(i)\t# copies this reply out — and a reject here rejects the outer session.
            \(i)\tupdate outer.session-state {
            \(i)\t\t\(SheepAttribute.handled) := "yes"
            \(i)\t}

            """
        }

        var body = ""
        if !active.isEmpty {
            body += """
            \(i)\t# ── Policy ▸ Rules ────────────────────────────────────────────────
            \(i)\t# The whole reply policy, in one list, top to bottom: FIRST MATCH WINS.
            \(i)\t# raddb/authorize carries only the password and the identity (Sheep-OU,
            \(i)\t# Sheep-Group) these conditions read. No rule matches = no VLAN in the
            \(i)\t# Access-Accept, and the port or SSID decides.
            \(i)\t#
            \(i)\t# Every comparison is paired with an existence test — `(&X && &X == "y")` —
            \(i)\t# because comparing an attribute that is not in the request is an ERROR in
            \(i)\t# unlang rather than false, and an error makes the whole `||` false even
            \(i)\t# when another branch is true.

            """
            if active.contains(where: { $0.needsWeekday }) {
                body += """
                \(i)\t# rlm_date's %a needs somewhere to read the time from: its xlat takes an
                \(i)\t# attribute name, not a literal.
                \(i)\tupdate control {
                \(i)\t\t\(weekdayHolder) := "%l"
                \(i)\t}

                """
            }
            body += walk(active[...], context: context, indent: i + "\t", startIndex: 0)
        }

        if !custom.isEmpty {
            body += """

            \(i)\t# ── Custom unlang (Policy ▸ Advanced) ────────────────────────────
            \(i)\t# Written verbatim, after the rules.

            """
            for line in custom.split(separator: "\n", omittingEmptySubsequences: false) {
                body += line.isEmpty ? "\n" : "\(i)\t\(line)\n"
            }
        }

        if inner {
            return out + body
        }
        // The outer copy is the one that has to be skipped for a tunnelled session.
        var guarded = """
        \(i)\t# Rules run here for everything that is not a PEAP / TTLS tunnel — PAP, CHAP,
        \(i)\t# MS-CHAP, and the EAP types with no inner tunnel. The inner-tunnel post-auth
        \(i)\t# sets &outer.session-state:\(SheepAttribute.handled) when it has already run them.
        \(i)\tif (!(&session-state:\(SheepAttribute.handled))) {

        """
        for line in body.split(separator: "\n", omittingEmptySubsequences: false).dropLast() {
            guarded += line.isEmpty ? "\n" : "\t\(line)\n"
        }
        guarded += "\(i)\t}\n"
        return out + guarded
    }
}

// MARK: - The Swift mirror

nonisolated enum RuleVerdict: String, Sendable, Hashable {
    /// The rule's conditions were true and its actions were applied.
    case matched
    /// Evaluated, did not match.
    case skipped
    /// An earlier rule matched and stopped the walk.
    case notReached
    case disabled
    /// A raw condition, which only radiusd can decide.
    case unknown
}

nonisolated struct RuleTrace: Sendable, Identifiable, Hashable {
    var id: UUID
    var index: Int
    var name: String
    var verdict: RuleVerdict
    var note: String = ""
}

/// One line of the final reply, with where it came from.
nonisolated struct PolicyLine: Sendable, Hashable, Identifiable {
    var id = UUID()
    var name: String
    var op: String
    var value: String
    /// A group name, "this user", or "rule: <name>".
    var source: String

    var line: String { "\(name) \(op) \(value)" }
}

nonisolated struct PolicyResult: Sendable {
    var lines: [PolicyLine] = []
    var rejected = false
    var rejectMessage = ""
    var traces: [RuleTrace] = []
    /// True when a raw condition meant a rule could not be decided here — the preview says so
    /// rather than pretending.
    var approximate = false

    var firedRules: [String] { traces.filter { $0.verdict == .matched }.map(\.name) }

    var vlan: String? {
        lines.last { $0.name == "Tunnel-Private-Group-Id" }?.value
            .trimmingCharacters(in: CharacterSet(charactersIn: "\""))
    }

    var attributeLines: [String] { lines.map(\.line) }
}

/// Three-valued, because a raw condition is neither true nor false until radiusd says so.
nonisolated enum Truth: Sendable {
    case yes, no, unknown

    var isYes: Bool { self == .yes }

    static func && (a: Truth, b: Truth) -> Truth {
        if a == .no || b == .no { return .no }
        if a == .unknown || b == .unknown { return .unknown }
        return .yes
    }

    static func || (a: Truth, b: Truth) -> Truth {
        if a == .yes || b == .yes { return .yes }
        if a == .unknown || b == .unknown { return .unknown }
        return .no
    }

    static prefix func ! (a: Truth) -> Truth {
        switch a {
        case .yes: .no
        case .no: .yes
        case .unknown: .unknown
        }
    }
}

// MARK: - The equivalence matrix
//
// The one test that makes two implementations of the same logic defensible.

/// A fixed rule set and a fixed set of requests, used by `./Tests/run.sh live` to prove that
/// `PolicyEvaluator` and the real radiusd reach the same answer.
///
/// It lives in the app rather than in the shell script because both halves of the comparison
/// have to be driven from here: the evaluator is Swift, and the request has to reach the real
/// server through the real client. `-policyMatrix 1` runs it and prints one line per request.
nonisolated enum PolicyMatrix {
    static let switchAddress = "10.20.0.0/24"
    /// This user's APs send Called-Station-Id as `<AP-GROUP>:<SSID>`, not `<AP MAC>:<SSID>`.
    /// The matrix drives that shape through both halves so the exact and the prefix condition
    /// are proved against the real radiusd, not only against the evaluator.
    static let apGroupPrefix = "SIAM-BUILDING:"
    static let apGroupCalledStationID = "SIAM-BUILDING:test2"
    static let apGroupOtherSSID = "SIAM-BUILDING:staff"
    static let otherAPGroupCalledStationID = "RAMA-BUILDING:test2"

    /// The document the probe applies: the sample lab's **own** rules — the three group rules,
    /// which are the whole static policy now — with eleven probe rules **above** them that
    /// between them use every condition kind the evaluator can decide and every action.
    ///
    /// The arrangement is the point of build 13: specific rules first, defaults last, first
    /// match wins. A probe rule that sets a VLAN therefore stops, or the group rule below would
    /// overwrite it — which is exactly the trap the pane's ordering note warns about, proved
    /// here against the real server rather than described.
    static func document(_ base: LabDocument, today: Date = Date()) -> LabDocument {
        var doc = base
        // "Visitors", not "Guests": the sample group was renamed in build 15 because AD owns
        // the name `Guests` domain-wide. The matrix drives the *sample* lab, so it has to
        // follow it. Names since build 21 — the same names the directory publishes as
        // `Sheep-Group` and the same ones the generated unlang compares against, so there is
        // nothing left that could resolve to nothing and quietly turn a two-condition rule
        // into a one-condition rule the matrix would then happily agree about.
        let guests = "Visitors"
        let admins = "NetAdmins"
        let staff = "Staff"
        let client = NASClient(name: "lab-switch", address: switchAddress, secret: "probe-secret")
        doc.clients = [client]
        doc.customUnlang = ""

        // The weekday conditions are pinned to *today* and to everything-but-today, so both
        // branches of the rlm_date lookup are exercised without the answer depending on when
        // the suite happens to run.
        var calendar = Calendar(identifier: .gregorian)
        calendar.locale = Locale(identifier: "en_US_POSIX")
        let weekday = calendar.component(.weekday, from: today)
        let mondayFirst = weekday == 1 ? 7 : weekday - 1
        let others = (1...7).filter { $0 != mondayFirst }

        doc.rules = [
            // 1 — two conditions, all of, and it stops. Guests on the guest SSID.
            PolicyRule(name: "probe-guest-ssid", match: .all, conditions: [
                RuleCondition(kind: .groupIs, value: guests),
                RuleCondition(kind: .ssid, value: "Lab-Guest"),
            ], stopAfterMatch: true, vlan: "99"),
            // 2 — a VLAN, so it has to stop: the group rule at the bottom would otherwise
            // replace it, which is first-match-wins working rather than failing.
            PolicyRule(name: "probe-wireless-admin", match: .all, conditions: [
                RuleCondition(kind: .groupIs, value: admins),
                RuleCondition(kind: .portType, value: RulePortType.wireless.rawValue),
            ], stopAfterMatch: true, vlan: "77", sessionTimeout: "3600"),
            // 3 — any-of, over the request-side conditions and a MAC in a third spelling.
            PolicyRule(name: "probe-any-of", match: .any, conditions: [
                RuleCondition(kind: .nasIdentifierIs, value: "sw-lab-1"),
                RuleCondition(kind: .callingMACIs, value: "aa:bb:cc:dd:ee:ff"),
                RuleCondition(kind: .nasIPInCIDR, value: "192.168.99.0/24"),
            ], stopAfterMatch: false, replyAttributes: "Class := \"probe-any\""),
            // 4 — the Clients table, and a regex on the username.
            PolicyRule(name: "probe-client-and-regex", match: .all, conditions: [
                RuleCondition(kind: .nasClient, reference: client.id),
                RuleCondition(kind: .usernameMatches, value: "^bo"),
            ], stopAfterMatch: false, replyAttributes: "Filter-Id := \"probe-client\""),
            // 5 — today, all day. Always true, which is what makes rule 6 meaningful.
            PolicyRule(name: "probe-today", match: .all, conditions: [
                RuleCondition(kind: .timeWindow, fromMinute: 0, toMinute: 1439, weekdays: [mondayFirst]),
                RuleCondition(kind: .ouIsUnder, value: "Staff"),
            ], stopAfterMatch: false, replyAttributes: "Reply-Message := \"probe-today\""),
            // 6 — every day but today: must never fire, or the weekday lookup is wrong.
            PolicyRule(name: "probe-not-today", match: .all, conditions: [
                RuleCondition(kind: .timeWindow, fromMinute: 0, toMinute: 1439, weekdays: others),
            ], stopAfterMatch: false, replyAttributes: "Reply-Message := \"probe-not-today\""),
            // 7 — group is NOT, and an exact OU.
            PolicyRule(name: "probe-not-admin-in-sales", match: .all, conditions: [
                RuleCondition(kind: .groupIsNot, value: admins),
                RuleCondition(kind: .ouIs, value: "Staff/Sales"),
            ], stopAfterMatch: false, sessionTimeout: "120"),
            // 8 — Reject, with a message, and it stops.
            PolicyRule(name: "probe-reject-virtual", match: .all, conditions: [
                RuleCondition(kind: .portType, value: RulePortType.virtual.rawValue),
            ], stopAfterMatch: true, rejects: true, rejectMessage: "probe says no"),
            // 9 — after a stopping rule, so it must be skipped whenever rule 8 fires.
            PolicyRule(name: "probe-after-stop", match: .all, conditions: [
                RuleCondition(kind: .groupIs, value: staff),
            ], stopAfterMatch: false, replyAttributes: "Class := \"probe-after-stop\""),
            // 10 — the whole Called-Station-Id, exactly. This user's APs send
            // "<AP-GROUP>:<SSID>", so the value has a hyphen and a colon in it.
            PolicyRule(name: "probe-called-exact", match: .all, conditions: [
                RuleCondition(kind: .calledStationIs, value: apGroupCalledStationID),
            ], stopAfterMatch: false, replyAttributes: "Filter-Id := \"probe-called-exact\""),
            // 11 — the prefix form: every SSID in that AP group. It must fire for rule 10's
            // request *and* for another SSID in the same group, and for nothing else. It sets
            // a VLAN, so like rule 2 it stops.
            PolicyRule(name: "probe-called-prefix", match: .all, conditions: [
                RuleCondition(kind: .calledStationBeginsWith, value: apGroupPrefix),
            ], stopAfterMatch: true, vlan: "88"),
            // 12 — an auto-named rule: no name of its own, so the tag radiusd prints is the
            // one the pane shows ("User bob → also send …"), arrow and all. Nothing else
            // proves that a generated name survives the config parser and the debug stream.
        ] + [
            PolicyRule(conditions: [RuleCondition(kind: .usernameEndsWith, value: "ob")],
                       stopAfterMatch: false, sessionTimeout: "45"),
        ] + base.rules
        return doc
    }

    /// The requests, each aimed at a user from the sample lab. `user` is a username.
    static func requests() -> [(name: String, user: String, request: PolicyRequest)] {
        [
            ("plain-alice", "alice", PolicyRequest(nasIPAddress: "127.0.0.1")),
            ("guest-on-guest-ssid", "guest",
             PolicyRequest(nasIPAddress: "127.0.0.1",
                           calledStationID: "00-11-22-33-44-55:Lab-Guest")),
            ("guest-on-other-ssid", "guest",
             PolicyRequest(nasIPAddress: "127.0.0.1",
                           calledStationID: "00-11-22-33-44-55:Lab-Staff")),
            ("alice-wireless", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", nasPortType: RulePortType.wireless.rawValue)),
            ("alice-wireless-and-nasid", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", nasIdentifier: "sw-lab-1",
                           nasPortType: RulePortType.wireless.rawValue)),
            ("alice-mac-cisco-spelling", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", callingStationID: "AABB.CCDD.EEFF")),
            ("alice-mac-dashes", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", callingStationID: "AA-BB-CC-DD-EE-FF")),
            ("alice-mac-other", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", callingStationID: "11:22:33:44:55:66")),
            ("bob-from-switch", "bob", PolicyRequest(nasIPAddress: "10.20.0.7")),
            ("alice-from-switch", "alice", PolicyRequest(nasIPAddress: "10.20.0.7")),
            ("bob-elsewhere", "bob", PolicyRequest(nasIPAddress: "127.0.0.1")),
            ("alice-in-cidr", "alice", PolicyRequest(nasIPAddress: "192.168.99.4")),
            ("virtual-port-rejects", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", nasPortType: RulePortType.virtual.rawValue)),
            ("guest-virtual-rejects-before-stop-rule", "guest",
             PolicyRequest(nasIPAddress: "127.0.0.1", nasPortType: RulePortType.virtual.rawValue)),
            ("ethernet-is-not-virtual", "bob",
             PolicyRequest(nasIPAddress: "127.0.0.1", nasPortType: RulePortType.ethernet.rawValue)),
            // The `<AP-GROUP>:<SSID>` trio: the exact value, another SSID in the same group,
            // and the same SSID in another group. Exact fires on the first only; the prefix
            // fires on the first two; neither fires on the third.
            ("alice-ap-group-exact", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", calledStationID: apGroupCalledStationID)),
            ("alice-ap-group-other-ssid", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", calledStationID: apGroupOtherSSID)),
            ("alice-other-ap-group", "alice",
             PolicyRequest(nasIPAddress: "127.0.0.1", calledStationID: otherAPGroupCalledStationID)),
        ]
    }

    /// The rows that are *also* driven through PEAP, once `eapol_test` made that possible.
    ///
    /// Not all fifteen: a tunnelled exchange is fifteen-odd round trips instead of one, and
    /// these five between them cover an untouched request, an SSID condition, a NAS-Identifier
    /// plus port-type condition, a station MAC, and a rule that rejects — which is the whole
    /// range of things `copy_request_to_tunnel` has to carry inside.
    static let tunnelledRows = ["plain-alice", "guest-on-guest-ssid", "alice-wireless-and-nasid",
                                "alice-mac-dashes", "virtual-port-rejects"]

    /// The comparable part of a fingerprint for a **tunnelled** session.
    ///
    /// A rejection decided inside the tunnel rejects the outer session — that is the point,
    /// and it is proved — but FreeRADIUS answers the outer request with a bare EAP-Failure,
    /// so none of the reply attributes come back out. Measured, including with an explicit
    /// `update outer.reply`, which does not change it. Comparing those attributes would
    /// therefore be comparing FreeRADIUS's tunnel behaviour and not the policy, so a reject
    /// is compared on the verdict and the rules that fired.
    static func tunnelled(_ fingerprint: String) -> String {
        guard fingerprint.hasPrefix("verdict=reject") else { return fingerprint }
        return fingerprint.split(separator: " ")
            .filter { $0.hasPrefix("verdict=") || $0.hasPrefix("rules=") }
            .joined(separator: " ")
    }

    /// One comparable string: the verdict, the VLAN, and every attribute a probe rule can set.
    /// Deliberately not "every attribute in the reply" — Message-Authenticator and friends are
    /// noise, and the point is what the *policy* decided.
    static let watched = ["Tunnel-Private-Group-Id", "Session-Timeout", "Filter-Id", "Class",
                          "Reply-Message"]

    /// `Class` is an `octets` attribute, so radclient prints it as `0x70726f…` — the same
    /// bytes, in the spelling its type calls for. Decoded here so the two sides of the
    /// comparison are comparing the value and not the notation.
    static func normalized(_ value: String) -> String {
        guard value.hasPrefix("0x"), value.count % 2 == 0 else { return value }
        let hex = value.dropFirst(2)
        guard !hex.isEmpty, hex.allSatisfy(\.isHexDigit) else { return value }
        var bytes: [UInt8] = []
        var index = hex.startIndex
        while index < hex.endIndex {
            let next = hex.index(index, offsetBy: 2)
            guard let byte = UInt8(hex[index..<next], radix: 16) else { return value }
            bytes.append(byte)
            index = next
        }
        guard let text = String(bytes: bytes, encoding: .utf8),
              !text.isEmpty, text.unicodeScalars.allSatisfy({ $0.value >= 32 && $0.value < 127 }) else {
            return value
        }
        return text
    }

    static func fingerprint(rejected: Bool, values: [String: String], rules: [String]) -> String {
        var parts = ["verdict=" + (rejected ? "reject" : "accept")]
        for name in watched {
            parts.append("\(name)=\(values[name].map(normalized) ?? "-")")
        }
        parts.append("rules=" + (rules.isEmpty ? "-" : rules.joined(separator: ",")))
        return parts.joined(separator: " ")
    }

    /// The evaluator's side of the comparison.
    static func predicted(user: LabUser, groupNames: [String], doc: LabDocument,
                          request: PolicyRequest) -> String {
        let result = PolicyEvaluator.evaluate(user: user, groups: groupNames.map { LabGroup(name: $0) },
                                              rules: doc.rules, context: PolicyContext(doc),
                                              request: request)
        var values: [String: String] = [:]
        for line in result.lines where watched.contains(line.name) {
            values[line.name] = line.value.trimmingCharacters(in: CharacterSet(charactersIn: "\""))
        }
        return fingerprint(rejected: result.rejected, values: values, rules: result.firedRules)
    }
}

// MARK: - One line for the Users and Groups panes

/// "rule 3 · Group NetAdmins → VLAN 10" — the whole of what Users and Groups say about RADIUS
/// (build 13). They used to carry an editable VLAN, a reply-attribute box and a resolved-reply
/// panel; now they carry this sentence and a link, because there is exactly one place a reply
/// is decided and this is not it.
///
/// Only the **user-side** half of a condition can be answered without a request, so a rule that
/// also tests an SSID or a NAS is reported as a candidate that "depends on the request" rather
/// than guessed at — the same honesty the Preview has always had about raw conditions.
nonisolated enum PolicySummary {
    nonisolated struct Line: Sendable, Equatable {
        /// "rule 3 · Group NetAdmins → VLAN 10", or the no-match sentence.
        var text: String
        var ruleID: UUID?
        /// False when the first candidate rule still needs something out of the request.
        var certain = true
    }

    static let noMatch = "no rule — VLAN of the port/SSID"

    static func forUser(_ user: LabUser, groupNames: [String], doc: LabDocument) -> Line {
        let context = PolicyContext(doc)
        let mine = groupNames.map { LabGroup(name: $0) }
        for (index, rule) in doc.rules.enumerated() where rule.enabled {
            let userSide = rule.conditions.filter { $0.kind.isUserSide }
            let requestSide = rule.conditions.count - userSide.count
            let truths = userSide.map {
                PolicyEvaluator.holds($0, user: user, groups: mine, context: context,
                                      request: PolicyRequest())
            }
            let name = "rule \(index + 1) · \(rule.displayName(index: index, context: context))"
            if rule.match == .all {
                if truths.contains(.no) { continue }
                let certain = requestSide == 0 && !truths.contains(.unknown)
                return Line(text: name, ruleID: rule.id, certain: certain)
            }
            // any-of: one true user-side condition is already enough.
            if truths.contains(.yes) { return Line(text: name, ruleID: rule.id, certain: true) }
            if requestSide > 0 || truths.contains(.unknown) {
                return Line(text: name, ruleID: rule.id, certain: false)
            }
        }
        return Line(text: noMatch, ruleID: nil)
    }

    /// **The user as the directory has them** — which since build 21 is the only way there is.
    ///
    /// A rule names its group, the directory names its groups, and the generated unlang
    /// compares `&control:Sheep-Group` by name: one vocabulary, end to end, with nothing to
    /// translate. A rule naming a group this user is not in simply does not match, which is
    /// the truthful answer.
    static func forDirectoryUser(_ user: DirectoryUser, doc: LabDocument) -> Line {
        forUser(LabUser(username: user.username, ou: user.ou), groupNames: user.groups, doc: doc)
    }

    /// And for a directory group: what a member of it and nothing else would get.
    static func forDirectoryGroup(_ group: DirectoryGroup, doc: LabDocument) -> Line {
        forUser(LabUser(username: ""), groupNames: [group.name], doc: doc)
    }
}

/// Predicts exactly what `RuleUnlang` will make radiusd do.
///
/// This is the pane's preview *and* the thing the live suite proves against the real server:
/// `./Tests/run.sh live` drives a matrix of requests through radclient and compares the reply
/// and the fired rules with this. If the two ever disagree, that test fails — which is the
/// only reason it is safe to have the logic written twice.
nonisolated enum PolicyEvaluator {

    static func evaluate(user: LabUser, groups: [LabGroup], rules: [PolicyRule],
                         context: PolicyContext, request: PolicyRequest) -> PolicyResult {
        // Build 13: there is no static reply to start from. The list *is* the policy, and a
        // request that matches nothing leaves with an Access-Accept and no VLAN.
        var result = PolicyResult()

        var stopped = false
        for (index, rule) in rules.enumerated() {
            let name = rule.displayName(index: index, context: context)
            guard rule.enabled else {
                result.traces.append(.init(id: rule.id, index: index, name: name, verdict: .disabled))
                continue
            }
            guard !stopped else {
                result.traces.append(.init(id: rule.id, index: index, name: name, verdict: .notReached))
                continue
            }
            let truth = matches(rule, user: user, groups: groups, context: context, request: request)
            switch truth {
            case .unknown:
                result.approximate = true
                result.traces.append(.init(id: rule.id, index: index, name: name, verdict: .unknown,
                                            note: "only radiusd can decide a raw condition"))
                // A rule that might match and might stop makes everything after it uncertain.
                if rule.stopAfterMatch { stopped = true }
            case .no:
                result.traces.append(.init(id: rule.id, index: index, name: name, verdict: .skipped))
            case .yes:
                result.traces.append(.init(id: rule.id, index: index, name: name, verdict: .matched))
                apply(rule, named: name, to: &result)
                if rule.stopAfterMatch { stopped = true }
            }
        }
        return result
    }

    /// `update reply { }` semantics: `:=` replaces every value of that attribute, `=` only
    /// sets it when it is not there, `+=` appends.
    private static func set(_ name: String, _ op: String, _ value: String, source: String,
                            in lines: inout [PolicyLine]) {
        switch op {
        case ":=":
            lines.removeAll { $0.name == name }
            lines.append(.init(name: name, op: op, value: value, source: source))
        case "=":
            guard !lines.contains(where: { $0.name == name }) else { return }
            lines.append(.init(name: name, op: op, value: value, source: source))
        default:
            lines.append(.init(name: name, op: op, value: value, source: source))
        }
    }

    private static func apply(_ rule: PolicyRule, named name: String, to result: inout PolicyResult) {
        let source = "rule: \(name)"
        let vlan = rule.vlan.trimmingCharacters(in: .whitespaces)
        if !vlan.isEmpty {
            set("Tunnel-Type", ":=", "VLAN", source: source, in: &result.lines)
            set("Tunnel-Medium-Type", ":=", "IEEE-802", source: source, in: &result.lines)
            set("Tunnel-Private-Group-Id", ":=", "\"\(ConfigGenerator.quoted(vlan))\"",
                source: source, in: &result.lines)
        }
        for attribute in rule.sentAttributes {
            set(attribute.name, attribute.op, attribute.value, source: source, in: &result.lines)
        }
        let timeout = rule.sessionTimeout.trimmingCharacters(in: .whitespaces)
        if rule.sendsAttributes, !timeout.isEmpty, Int(timeout) != nil {
            set("Session-Timeout", ":=", timeout, source: source, in: &result.lines)
        }
        let message = rule.rejectMessage.trimmingCharacters(in: .whitespaces)
        if rule.rejects {
            if !message.isEmpty {
                set("Reply-Message", ":=", "\"\(ConfigGenerator.quoted(message))\"", source: source, in: &result.lines)
                result.rejectMessage = message
            }
            result.rejected = true
        }
    }

    // MARK: Conditions

    static func matches(_ rule: PolicyRule, user: LabUser, groups: [LabGroup],
                        context: PolicyContext, request: PolicyRequest) -> Truth {
        let truths = rule.conditions.map { holds($0, user: user, groups: groups, context: context, request: request) }
        guard !truths.isEmpty else { return .yes }
        return rule.match == .all
            ? truths.reduce(Truth.yes) { $0 && $1 }
            : truths.reduce(Truth.no) { $0 || $1 }
    }

    static func holds(_ c: RuleCondition, user: LabUser, groups: [LabGroup],
                      context: PolicyContext, request: PolicyRequest) -> Truth {
        let value = c.value.trimmingCharacters(in: .whitespaces)
        switch c.kind {
        case .groupIs, .groupIsNot:
            let name = value
            guard !name.isEmpty else { return .no }
            // `==` on a string is case-sensitive in unlang, so it is here too.
            let member = groups.contains { $0.name == name }
            return c.kind == .groupIs ? truth(member) : truth(!member)
        case .ouIs:
            let path = OUPath.normalized(value)
            guard !path.isEmpty else { return .no }
            return truth(user.effectiveOU == path)
        case .ouIsUnder:
            let path = OUPath.normalized(value)
            guard !path.isEmpty else { return .no }
            let mine = user.effectiveOU
            return truth(mine == path || mine.hasPrefix(path + "/"))
        case .usernameIs:
            guard !value.isEmpty else { return .no }
            return truth(user.username == value)
        case .usernameEndsWith:
            guard !value.isEmpty else { return .no }
            return truth(user.username.hasSuffix(value))
        case .usernameMatches:
            guard !value.isEmpty else { return .no }
            return truth(matchesRegex(user.username, value, caseInsensitive: false))
        case .nasIPIs:
            guard Validation.isValidAddress(value), !value.contains("/") else { return .no }
            return truth(ipv4(request.nasIPAddress) != nil && ipv4(request.nasIPAddress) == ipv4(value))
        case .nasIPInCIDR:
            guard Validation.isValidAddress(value) else { return .no }
            return truth(inside(request.nasIPAddress, value))
        case .nasClient:
            guard let address = context.clientAddress(c.reference), Validation.isValidAddress(address) else { return .no }
            return truth(inside(request.nasIPAddress, address))
        case .nasIdentifierIs:
            guard !value.isEmpty else { return .no }
            return truth(request.nasIdentifier == value)
        case .nasIdentifierMatches:
            guard !value.isEmpty else { return .no }
            return truth(!request.nasIdentifier.isEmpty
                         && matchesRegex(request.nasIdentifier, value, caseInsensitive: false))
        case .portType:
            guard let type = RulePortType(rawValue: value) else { return .no }
            return truth(request.nasPortType == type.rawValue)
        case .ssid:
            guard !value.isEmpty else { return .no }
            return truth(request.calledStationID.hasSuffix(":" + value))
        case .calledStationIs:
            guard !value.isEmpty else { return .no }
            return truth(request.calledStationID == value)
        case .calledStationBeginsWith:
            guard !value.isEmpty else { return .no }
            return truth(!request.calledStationID.isEmpty && request.calledStationID.hasPrefix(value))
        case .callingMACIs:
            guard let digits = RuleUnlang.macDigits(value),
                  let sent = RuleUnlang.macDigits(request.callingStationID) else { return .no }
            return truth(digits == sent)
        case .callingMACMatches:
            guard !value.isEmpty else { return .no }
            return truth(!request.callingStationID.isEmpty
                         && matchesRegex(request.callingStationID, value, caseInsensitive: true))
        case .timeWindow:
            return truth(inWindow(c, at: request.date))
        case .anyone:
            return .yes
        case .isComputerAccount:
            // The evaluator is only ever asked about a person — Users ▸ Properties and the
            // Preview strip both start from a `LabUser`, and a machine account is never one.
            // The tag is still tested rather than answered `.no` outright, so a lab that
            // really does have a group of that name previews the way radiusd will behave.
            return truth(groups.contains { $0.name == MachineIdentity.groupTag })
        case .raw:
            return value.isEmpty ? .no : .unknown
        }
    }

    private static func truth(_ b: Bool) -> Truth { b ? .yes : .no }

    /// Local calendar, matching `%H%G` and rlm_date's `%a`, both of which radiusd renders in
    /// this Mac's own time zone.
    static func inWindow(_ c: RuleCondition, at date: Date) -> Bool {
        let days = c.normalizedWeekdays
        guard !days.isEmpty else { return false }
        var calendar = Calendar(identifier: .gregorian)
        calendar.locale = Locale(identifier: "en_US_POSIX")
        let parts = calendar.dateComponents([.hour, .minute, .weekday], from: date)
        guard let hour = parts.hour, let minute = parts.minute, let weekday = parts.weekday else { return false }
        // Calendar's weekday is 1 = Sunday; the model is 1 = Monday.
        let mondayFirst = weekday == 1 ? 7 : weekday - 1
        if days.count < 7, !days.contains(mondayFirst) { return false }
        guard !c.isAllDay else { return true }
        let now = hour * 100 + minute
        let from = clock(c.fromMinute), to = clock(c.toMinute)
        return c.fromMinute <= c.toMinute ? (now >= from && now <= to) : (now >= from || now <= to)
    }

    private static func clock(_ minutes: Int) -> Int {
        let clamped = max(0, min(1439, minutes))
        return (clamped / 60) * 100 + clamped % 60
    }

    /// The same partial match `=~` performs — unanchored unless the pattern says otherwise.
    static func matchesRegex(_ subject: String, _ pattern: String, caseInsensitive: Bool) -> Bool {
        guard let regex = try? NSRegularExpression(
            pattern: pattern, options: caseInsensitive ? [.caseInsensitive] : []) else { return false }
        let range = NSRange(subject.startIndex..., in: subject)
        return regex.firstMatch(in: subject, options: [], range: range) != nil
    }

    /// Dotted quad → host order, or nil.
    static func ipv4(_ s: String) -> UInt32? {
        let parts = s.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 4 else { return nil }
        var out: UInt32 = 0
        for part in parts {
            guard let octet = UInt8(part) else { return nil }
            out = (out << 8) | UInt32(octet)
        }
        return out
    }

    /// True when `address` falls inside `pattern`, which may be a single IP or a CIDR.
    static func inside(_ address: String, _ pattern: String) -> Bool {
        guard let value = ipv4(address) else { return false }
        let pieces = pattern.split(separator: "/", omittingEmptySubsequences: false)
        guard let network = ipv4(String(pieces[0])) else { return false }
        guard pieces.count == 2 else { return value == network }
        guard let bits = Int(pieces[1]), (0...32).contains(bits) else { return false }
        if bits == 0 { return true }
        let mask: UInt32 = bits == 32 ? .max : ~(UInt32.max >> UInt32(bits))
        return (value & mask) == (network & mask)
    }
}
